- Docs/Reference.dox
- Source/ThirdParty/STB/stb_rect_pack.h
- Source/Tools/SpritePacker/CMakeLists.txt
- Source/Tools/SpritePacker/SpritePacker.cpp
This is a basic cli program that packs a bunch of pngs into a single large one and generates an urho3d specific xml file.
> SpritePacker cli

- Source/Urho3D/UI/View3D.cpp
A fix for a type in the View3D size check
> Fix typo in View3D size check

- Docs/Reference.dox
Updates to navigation documentation and request for comments on what everyone feels is important to cover versus what's overkill.
> Updates to Navigation documentation

- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorSettings.as
- bin/Data/Scripts/Editor/EditorView.as
- bin/Data/UI/EditorSettingsDialog.xml
Another methods for determining positions for new nodes
> Editor new node position

- Docs/AngelScriptAPI.h
- Docs/LuaScriptAPI.dox
- Docs/Reference.dox
- Docs/ScriptAPI.dox
- Docs/Urho3D.dox
- Source/Samples/40_Localization/CMakeLists.txt
- Source/Samples/40_Localization/L10n.cpp
- Source/Samples/40_Localization/L10n.h
- Source/Samples/CMakeLists.txt
- Source/Urho3D/Engine/Engine.cpp
- Source/Urho3D/LuaScript/pkgs/Resource/Localization.pkg
- Source/Urho3D/LuaScript/pkgs/ResourceLuaAPI.pkg
- Source/Urho3D/LuaScript/pkgs/UI/Text.pkg
- Source/Urho3D/Resource/Localization.cpp
- Source/Urho3D/Resource/Localization.h
- Source/Urho3D/Resource/ResourceEvents.h
- Source/Urho3D/Script/ResourceAPI.cpp
- Source/Urho3D/Script/UIAPI.cpp
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/Text.h
- bin/Data/EditorStrings.json
- bin/Data/LuaScripts/40_Localization.lua
- bin/Data/Scripts/40_Localization.as
- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorResourceBrowser.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/StringsDe.json
- bin/Data/StringsEnRu.json
- bin/Data/UI/EditorResourceBrowser.xml
- bin/EditorRu.bat
> Internationalization

- Docs/GettingStarted.dox
- bin/Data/EditorStrings.json
- bin/Data/Scripts/Editor/EditorActions.as
- bin/Data/Scripts/Editor/EditorHierarchyWindow.as
- bin/Data/Scripts/Editor/EditorLayers.as
- bin/Data/Scripts/Editor/EditorScene.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/Scripts/Editor/EditorView.as
This feature allows fast instantiate one model for StaticModelGroup.
You start with single node with one Static model within.
Then you do first pressing ( alt+d) it create a static model group with first instance of model you need to move it somewhere and  next pressing on alt+d just add new instances.
see this in work: https://youtu.be/YOGpdieVCUE
> Smart instance

- bin/Data/EditorStrings.json
Added french strings, so the editor should be able to support french
> French strings addon

- bin/Data/Scripts/Editor/EditorLayers.as
easiest way to solve this https://github.com/urho3d/Urho3D/issues/810 in b.mode
> fixed missing event handler from color wheel after layer using

- bin/Data/EditorStrings.json
Updated the french language:
- Added new strings for the new terms
- Changed some whitespaces to tabs
- Improved translation
-Tested in editor
> Updated french language

- Source/Urho3D/Math/Color.h
- Source/Urho3D/Math/Plane.h
- Source/Urho3D/Math/Polyhedron.h
- Source/Urho3D/Math/Vector2.h
Added assign operator since there is a copy constructor. (More consistent)
> Added = operator

- .gitignore
- Source/Urho3D/Container/Str.cpp
- Source/Urho3D/Container/Str.h
- Source/Urho3D/Core/Spline.cpp
- Source/Urho3D/Input/Input.cpp
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/UI/FontFaceBitmap.cpp
- Source/Urho3D/UI/UIElement.cpp
> Wrong Casting

- Source/ThirdParty/kNet/include/kNet/Lockable.h
- Source/Urho3D/Math/AreaAllocator.cpp
- Source/Urho3D/Math/AreaAllocator.h
- Source/Urho3D/Script/Script.h
- Source/Urho3D/Script/ScriptAPIDump.cpp
Fixed some parameters wrongly passed by value
> Const references

- Source/Urho3D/Urho2D/CollisionShape2D.cpp
- Source/Urho3D/Urho2D/RigidBody2D.cpp
fix https://github.com/urho3d/Urho3D/issues/839
> fix add RigidBody2D after CollisionShape2D

- bin/Data/EditorStrings.json
Added Italian language to the editor.
> Italian localization

- bin/Data/Scripts/Editor/EditorScene.as
little fix then you typing text into LineEdit, do not show LayerEditor.
> fix-m-typing

- Docs/Reference.dox
No longer relevant since change 094d146c3c55e1836c91feb761d0227906bdadfb.
> Removed outdated warning in TMX documentation

- Source/Urho3D/Graphics/DebugRenderer.cpp
- Source/Urho3D/Graphics/DebugRenderer.h
- Source/Urho3D/LuaScript/pkgs/Graphics/DebugRenderer.pkg
- Source/Urho3D/Script/GraphicsAPI.cpp
sorry, I`m not familiar with lua scripting, so this pull request only tested with angel script.
> add method for circle,cross,quad debug renderering

- Source/Urho3D/Math/Quaternion.cpp
Optimize Quaternion::Slerp() to remove the costly trigonometric functions and replace them by approximations instead. The approximations have been profiled to generate a maximum interpolation error of 0.38 degrees (see test Quat_Slerp_precision in MathGeoLib). In native 64bit Windows 8.1 VS2015 builds, testing in 06_SkeletalAnimation sample with 2000 Jacks, the time taken in Quaternion::Slerp() is reduced by -17.4%, and in Emscripten build of the same sample running in Firefox 41, the time taken by Quaternion::Slerp() is reduced by -44.7%. Closes #914.
> approx_quat_slerp

- Source/Samples/06_SkeletalAnimation/SkeletalAnimation.cpp
- bin/Data/LuaScripts/06_SkeletalAnimation.lua
- bin/Data/Scripts/06_SkeletalAnimation.as
Make Jacks not walk in synchronized lockstep timing in 06_SkeletalAnimation sample.
> unsynchronized_jacks

- Source/Urho3D/Math/Quaternion.h
SSE optimizes functions in Quaternion.h.
> sse_opt_quat

- Source/Urho3D/UI/UI.cpp
Since E_UIMOUSECLICK is triggered also over no element most people want the same effect with E_UIMOUSEDOUBLECLICK
> Trigger double-click event over no element

- bin/Data/Scripts/Editor/EditorHierarchyWindow.as
- bin/Data/Scripts/Editor/EditorInspectorWindow.as
- bin/Data/Scripts/Editor/EditorMaterial.as
- bin/Data/Scripts/Editor/EditorParticleEffect.as
- bin/Data/Scripts/Editor/EditorPreferences.as
- bin/Data/Scripts/Editor/EditorResourceBrowser.as
- bin/Data/Scripts/Editor/EditorSettings.as
- bin/Data/Scripts/Editor/EditorSoundType.as
- bin/Data/Scripts/Editor/EditorSpawn.as
- bin/Data/Scripts/Editor/EditorUI.as
- Pressing return key executes the top "Quick Action" result
- Windows toggle with the "Show ____" commands.
- ie. CTRL+I toggles inspector visible/hidden
> Urho3D Editor Workflow speed enhancements

- bin/Data/Scripts/Editor/EditorSpawn.as
- bin/Data/UI/EditorSpawnWindow.xml
Offset in local space for node in Spawn Editor.
> Urho3D Editor: Local offset for Spawn Editor

- bin/Data/Scripts/Editor/EditorSpawn.as
- bin/Data/UI/EditorSpawnWindow.xml
It allow to spawn only on selected node, ex. grass on terrain through
trees, also not spawn on previous inserted nodes.
> Urho3D Editor: Spawn on selected node in Spawn Editor

- bin/Data/Scripts/Editor/EditorParticleEffect.as
- bin/Data/Scripts/Editor/EditorView.as
It is necessary for custom RenderPath like Soft Particle http://urho3d.prophpbb.com/topic1611.html
> Editor: set RenderPath for particle editor

- Source/Urho3D/Navigation/CrowdAgent.cpp
- Source/Urho3D/Navigation/NavigationEvents.h
- Source/Urho3D/Navigation/NavigationMesh.cpp
- Source/Urho3D/Navigation/NavigationMesh.h
Made CrowdAgent emit events from the attached Node as well as the
associated CrowdManager, to allow for simpler reaction of other
components on the same Node to crowd agent events.
> Made CrowdAgent emit events the attached Node as well

- bin/CoreData/Shaders/GLSL/Skydome.glsl
- bin/CoreData/Shaders/HLSL/Skydome.hlsl
- bin/CoreData/Techniques/DiffSkydome.xml
Update on Skydome adding shaders and technique.
> Added Skydome Shaders and Technique

- bin/Data/Scripts/Editor/EditorInspectorWindow.as
I forgot check scene tags in manner like default tags
this is quick fix for this.
> fix double adding tag from scene

- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Math/Matrix2.pkg
- Source/Urho3D/LuaScript/pkgs/Math/Vector2.pkg
- Source/Urho3D/Math/Matrix2.cpp
- Source/Urho3D/Math/Matrix2.h
- Source/Urho3D/Math/Vector2.h
A Matrix2 class seemed to be missing from Urho3D.
> Added Matrix2 class

- Source/Urho3D/Graphics/Drawable.cpp
Checkout this, please. There is just few fixes for exporter.
> fix obj exporter bugs

- Source/Urho3D/IO/FileWatcher.cpp
```inotify_rm_watch()``` will cause a watching thread to return from ```read()```, but this was not possible because the thread was being joined before calling ```inotify_rm_watch()```
I moved the call to ```Stop()``` in ```FileWatcher::StopWatching()``` after the call to ```inotify_rm_watch()``` and also ifdef'd the small hack with creating and deleting a file.
> fixes #1196 - Filewatcher no longer gets stuck in read() (on linux only)

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/AnimationController.cpp
- Source/Urho3D/Graphics/AnimationController.h
- Source/Urho3D/Graphics/AnimationState.cpp
- Source/Urho3D/Graphics/AnimationState.h
- Source/Urho3D/LuaScript/pkgs/Graphics/AnimationController.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/AnimationState.pkg
I try to make additive blending for animations. It works, but flickering every cycle, and I do not know why. Test scene: https://github.com/1vanK/MyFiles/raw/master/Temp/AnimationBlendTest.zip (need add CoreData and Data folders)
> Additive animation blending

- Source/Urho3D/Core/Context.h
So we can create objects like:
context_->CreateObject<MyType>()
Just like creating components.
> Convenience method Context::CreateObject<T>()

- Source/Tools/AssetImporter/AssetImporter.cpp
Example:
c:/>AssetImporter model xxx.fbx xxx.mdl -split 10 40
You will get a .ani file only with subanimation from frame 10 to frame 40.
> AssetImporter can import a subset animation frames.

- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.h
- Source/Urho3D/Graphics/Direct3D9/D3D9Graphics.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9Graphics.h
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.h
only  supported for opengl 3  and direct3d
> Add Graphics draw call with base vertex index (Offset Indexing)

- Source/Urho3D/Container/HashMap.h
- Source/Urho3D/Container/Vector.h
added TryGetValue and Insert for the HashMap class
and added EraseSwap and RemoveSwap for the Vector class
i needed them for my game ...
i also have a SortedVector and SparseVector implementation that could be merged too ....
> Extend Vector and HashMap 

- Source/Tools/AssetImporter/AssetImporter.cpp
- bin/Data/Scripts/Editor/EditorImport.as
- bin/Data/Scripts/Editor/EditorUI.as
simple import only animation option for the AssetImporter. 
added "Import Animation" menu item to the editor.
this works for my animations ...
> Add import only animation

- Source/Samples/43_HttpRequestDemo/CMakeLists.txt
- Source/Samples/43_HttpRequestDemo/HttpRequestDemo.cpp
- Source/Samples/43_HttpRequestDemo/HttpRequestDemo.h
- bin/Data/LuaScripts/43_HttpRequestDemo.lua
- bin/Data/Scripts/43_HttpRequestDemo.as
Commited just AngelScript version for now to avoid CI failure as require #1381 to be merged first. (Lua version have some issues with Deserializer API, I need to investigate because may be a bug in Urho3D/tolua++).
> Add Http Request demo sample.

- Source/Urho3D/UI/UI.cpp
Required for some animated effects
> Send elapsedTime to UI shader

- Source/Urho3D/Container/Str.cpp
> fix a typo in UTF16 decoder

- Source/ThirdParty/Civetweb/src/civetweb.c
https://github.com/urho3d/Urho3D/issues/1444
> fixes #1444

- Source/Urho3D/Container/Ptr.h
- Source/Urho3D/Container/Vector.h
> Minor changes in Container

- Source/Urho3D/Urho2D/RigidBody2D.h
to be consistent with set functions.
> get body properties when body exists

- Source/Urho3D/Graphics/Viewport.h
sorry for this second pull-request. i've found the same issue in another file but my previous pull-request was already merged.
> Normal comment to doxygen comment.

- Source/Urho3D/Container/HashMap.h
> Make HashMap::TryGetValue constant.

- bin/Data/LuaScripts/42_PBRMaterials.lua
- bin/Data/Scenes/PBRExample.xml
- bin/Data/Scripts/42_PBRMaterials.as
- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorSettings.as
- bin/Data/Scripts/Editor/EditorView.as
- bin/Data/UI/EditorSettingsDialog.xml
Changes include the following:
Removed Bloom from PBR demo,
Set zone texture ambleint to 1,
Added HDR option in editor settings (needed for PBR in editor)
> Fixes to PBR demo and HDR option in editor so PBR displays correct

- bin/Data/UI/DefaultStyle.xml
I believe that it is how it should be by default, it is not a MultiLineEdit so it should be centered Vertically
http://i.imgur.com/qjAYO0f.png
> Make LineEdit text and cursor to be always verticaly centered

- Source/Tools/AssetImporter/AssetImporter.cpp
-also removed dbg dump code and minor spelling changes
> fixed channelIndices[] indexing in ExpandAnimatedChannelKeys() func.

- Source/Tools/SpritePacker/SpritePacker.cpp
fix delete typo in SpritePacker.cpp
> fix delete in SpritePacker.cpp

- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Resource/Image.h
> Add functions for mipmap manipulation to Image.

- Source/Urho3D/Container/Vector.h
- Source/Urho3D/Graphics/StaticModel.cpp
- Source/Urho3D/Graphics/StaticModel.h
- Source/Urho3D/Scene/Serializable.h
Closes #1608 
Closes #1605 
And also add Resize overload that I've found useful.
> Minor changes

- bin/CoreData/Shaders/HLSL/Skybox.hlsl
PS. GLSL version don't have such problem
> Fix error in Skybox.hlsl when instancing is forced on.

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Math/Vector2.pkg
- Source/Urho3D/LuaScript/pkgs/Scene/Node.pkg
- Source/Urho3D/Math/Vector2.h
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
- Source/Urho3D/UI/UIElement.cpp
- Source/Urho3D/UI/UIElement.h
First of all - im sorry, i know it should be one PR per feature, but i did not want to flood project with 5-line PRs. If anything is not agreeable i will overwrite these commits based on discussion for a clean merge in the end.
For my own needs i added bunch of utility functions that ease life. 
`UIElement::FindChildrenWithTag()` and `Node::GetChildren*()` functions that return vectors with results. This is very convenient as it allows to use said functions in modern c++ loops like `for (auto child : node->GetChildren())`. It also is not a performance issue if modern compiler is used since compilers rewrite calls that return objects by value to calls that receive variable by reference for storing return value.
`IntVector2::Length()` - self explanatory.
`Node::SetTransform(const Matrix3x4& …
> Utility functions

- Source/Urho3D/AngelScript/Urho2DAPI.cpp
- Source/Urho3D/Core/Variant.cpp
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/LuaScript/pkgs/Urho2D/StaticSprite2D.pkg
- Source/Urho3D/Urho2D/StaticSprite2D.cpp
- Source/Urho3D/Urho2D/StaticSprite2D.h
This PR adds function to override the draw and texture rectangles of a StaticSprite2D
> Added SetDrawRect and SetTextureRect in StaticSprite2D

- Source/Urho3D/Urho2D/ConstraintDistance2D.cpp
- Source/Urho3D/Urho2D/ConstraintDistance2D.h
- Source/Urho3D/Urho2D/ConstraintFriction2D.cpp
- Source/Urho3D/Urho2D/ConstraintGear2D.cpp
- Source/Urho3D/Urho2D/ConstraintMotor2D.cpp
- Source/Urho3D/Urho2D/ConstraintMouse2D.cpp
- Source/Urho3D/Urho2D/ConstraintMouse2D.h
- Source/Urho3D/Urho2D/ConstraintPrismatic2D.cpp
- Source/Urho3D/Urho2D/ConstraintRevolute2D.cpp
- Source/Urho3D/Urho2D/ConstraintRope2D.cpp
- Source/Urho3D/Urho2D/ConstraintWeld2D.cpp
- Source/Urho3D/Urho2D/ConstraintWheel2D.cpp
This PR contains improved handling for several constraints. I checked it in Urho2DConstraints example and it seems to work fine. Moreover I have added SetLimit and GetLimit for distance constraint.
> Improve Box2D joints handling, fixes #1787

- Source/Samples/40_Localization/L10n.cpp
- bin/Data/LuaScripts/40_Localization.lua
- bin/Data/Scripts/40_Localization.as
> Fixing small typos in comments

- Source/Urho3D/Urho2D/PhysicsWorld2D.h
Need access to ContactInfo type
> Allow access to PhysicsWorld2D members from chield classes

- Source/Urho3D/AngelScript/CoreAPI.cpp
- Source/Urho3D/AngelScript/ResourceAPI.cpp
- Source/Urho3D/Core/StringUtils.cpp
- Source/Urho3D/Core/StringUtils.h
- Source/Urho3D/Core/Variant.cpp
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/IO/Deserializer.cpp
- Source/Urho3D/IO/Serializer.cpp
- Source/Urho3D/LuaScript/ToluaUtils.cpp
- Source/Urho3D/LuaScript/pkgs/Core/StringUtils.pkg
- Source/Urho3D/LuaScript/pkgs/Core/Variant.pkg
- Source/Urho3D/LuaScript/pkgs/Resource/XMLElement.pkg
- Source/Urho3D/Resource/XMLElement.cpp
- Source/Urho3D/Resource/XMLElement.h
Title ^. Please make sure i did not forget anything here.
> 64bit integer variant

- Docs/Urho3D.dox
As discussed [here](http://discourse.urho3d.io/t/next-release/2031/13).
> Added heXon and Quatter to external links

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/Animation.cpp
- Source/Urho3D/Graphics/Animation.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Animation.pkg
This variant of Animation::GetTrack() is listed in the documentation but I couldn't see it implemented anywhere in the source code.
> Add Animation::GetTrack(unsigned)

- Source/Urho3D/Math/Vector2.cpp
- Source/Urho3D/Math/Vector2.h
> IntVector2 constants

- Source/Urho3D/UI/UI.cpp
Root UI element can be resized, however setting it's position renders UI with bottom and right portions cut-off. Change fixes the issue and resized/positioned root UI element is rendered properly.
Before anyone asks - tested `GetElementAt()` and it works properly ;)
> Allow root UI element to be moved.

- Source/Samples/46_RaycastVehicle/CMakeLists.txt
- Source/Samples/46_RaycastVehicle/RaycastVehicleDemo.cpp
- Source/Samples/46_RaycastVehicle/RaycastVehicleDemo.h
- Source/Samples/46_RaycastVehicle/Vehicle.cpp
- Source/Samples/46_RaycastVehicle/Vehicle.h
- Source/Urho3D/AngelScript/PhysicsAPI.cpp
- Source/Urho3D/AngelScript/ScriptAPI.h
- Source/Urho3D/Engine/Engine.cpp
- Source/Urho3D/LuaScript/pkgs/Physics/RaycastVehicle.pkg
- Source/Urho3D/LuaScript/pkgs/PhysicsLuaAPI.pkg
- Source/Urho3D/Physics/RaycastVehicle.cpp
- Source/Urho3D/Physics/RaycastVehicle.h
- bin/Data/LuaScripts/46_RaycastVehicleDemo.lua
- bin/Data/Particle/Dust.xml
- bin/Data/Scripts/46_RaycastVehicleDemo.as
Hi!
This is initial release of RaycastVehicle component, which is wrapping of Bullet btRaycastVehicle.
Many features are missing, which will be added later.
The commit contains C++ code and AngelScript + Lua binding. But there is no Lua demo yet.
The component is not able to save/load yet (don't know how to do it).
The purpose of this PR is to recieve feedback and review. Please remember that:
It is my first submission and many things can be wrong. Please have patience and explain to me
what is wrong, I'll be more than happy to fix all things. Especially coding style errors might happen.
I'm from C/Linux kernel/MCU scenery and have very little (VERY little) C++ experience.
So please comment on general design errors, if I'm doing something wrong in general.
I have very little experience …
> Bullet RaycastVehicle support

- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/AngelScript/ScriptFile.cpp
- Source/Urho3D/LuaScript/pkgs/Math/Quaternion.pkg
- Source/Urho3D/Math/Quaternion.cpp
- Source/Urho3D/Math/Quaternion.h
Added helper function to get an axis/angle from Quaternion.
Also fixed a bug when Urho crashes if AS ScriptObject throw an exception from ctor.
> Minor fix and helper function

- Source/Urho3D/Physics/RaycastVehicle.h
> Fix missing #pragma once;

- CMake/Modules/UrhoCommon.cmake
- Docs/AngelScriptAPI.h
- Docs/LuaScriptAPI.dox
- Docs/ScriptAPI.dox
- Source/Urho3D/AngelScript/CoreAPI.cpp
- Source/Urho3D/Core/ProcessUtils.cpp
- Source/Urho3D/Core/ProcessUtils.h
- Source/Urho3D/LuaScript/pkgs/Core/ProcessUtils.pkg
Continuation of PR #1931 
Looks good on my machine. Only supports Windows and Linux platform at the moment. The Windows API used requires Windows 2000 Pro/XP or higher.
> Platform-specific system query functions

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/Model.cpp
- Source/Urho3D/Graphics/Model.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Model.pkg
Minor improvement.
Let it be CI-ed before merge...
> Add Model metadata support.

- Source/Urho3D/AngelScript/CoreAPI.cpp
- Source/Urho3D/Core/Object.cpp
- Source/Urho3D/Navigation/CrowdAgent.h
- Source/Urho3D/Navigation/Obstacle.h
> Prevent sending events for subscribers added during event handling.

- Docs/Doxyfile.in
- Docs/Reference.dox
- Docs/Urho3D.dox
> IK documentation

- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Math/Rect.pkg
- Source/Urho3D/Math/Rect.cpp
- Source/Urho3D/Math/Rect.h
I added a few utility functions to IntRect for better parity with Rect.
> Added Clip, Merge, and contructor from pair of IntVector2 to IntRect.

- Source/Urho3D/Core/Variant.cpp
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/LuaScript/ToluaUtils.cpp
I removed those nasty reinterpret casts from Variant. Also added int64 to float/double casts in getters and fixed cast in `op == (ULL)`
> Refactor Variant (part #1)

- Docs/Urho3D.dox
- Source/Urho3D/AngelScript/CoreAPI.cpp
- Source/Urho3D/AngelScript/SceneAPI.cpp
- Source/Urho3D/Core/Attribute.h
- Source/Urho3D/Core/Context.cpp
- Source/Urho3D/Core/Context.h
- Source/Urho3D/Graphics/AnimatedModel.cpp
- Source/Urho3D/Graphics/BillboardSet.cpp
- Source/Urho3D/Graphics/StaticModelGroup.cpp
- Source/Urho3D/Navigation/CrowdManager.cpp
- Source/Urho3D/Physics/RaycastVehicle.cpp
- Source/Urho3D/Scene/Serializable.h
- Source/Urho3D/Scene/SplinePath.cpp
- bin/Data/Scripts/Editor/AttributeEditor.as
It's probably better to merge this part separately.
Resolves #1766.
> Add attribute metadata.

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/Scene/ValueAnimation.cpp
- Source/Urho3D/Scene/ValueAnimation.h
* Fix crash in AS named object constructor
* Make ValueAnimation::GetAnimationValue const
> Fix crash in AS named object constructor & minor refactoring

- Source/Urho3D/LuaScript/LuaScript.cpp
> Switch Lua gc mode to incremental step

- Source/Samples/32_Urho2DConstraints/Urho2DConstraints.cpp
Fixed failing for picking rigidbody on touch devices.
> Fixed failing for picking rigidbody.

- Docs/Reference.dox
- Source/Samples/01_HelloWorld/HelloWorld.cpp
- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Core/Attribute.h
- Source/Urho3D/Graphics/Light.cpp
- Source/Urho3D/Graphics/Light.h
- Source/Urho3D/Graphics/Octree.cpp
- Source/Urho3D/Graphics/Octree.h
- Source/Urho3D/Graphics/Terrain.cpp
- Source/Urho3D/Graphics/Terrain.h
- Source/Urho3D/Graphics/View.cpp
- Source/Urho3D/Graphics/Zone.cpp
- Source/Urho3D/Graphics/Zone.h
- Source/Urho3D/Math/Vector4.h
- Source/Urho3D/Navigation/OffMeshConnection.cpp
- Source/Urho3D/Navigation/OffMeshConnection.h
- Source/Urho3D/Physics/CollisionShape.cpp
- Source/Urho3D/Physics/CollisionShape.h
- Source/Urho3D/Physics/Constraint.cpp
- Source/Urho3D/Physics/Constraint.h
- Source/Urho3D/Physics/RigidBody.cpp
- Source/Urho3D/Physics/RigidBody.h
- Source/Urho3D/Scene/Serializable.cpp
- Source/Urho3D/Scene/Serializable.h
- Source/Urho3D/Urho2D/Constraint2D.cpp
- Source/Urho3D/Urho2D/Constraint2D.h
> Attribute refactoring

- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Math/Color.pkg
- Source/Urho3D/Math/Color.cpp
- Source/Urho3D/Math/Color.h
Closes #2179.
This is my first contribution of substance to any open source project, so please, leave any comments on how to improve.
> Add Color::FromUInt.

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/Graphics/Skeleton.cpp
- Source/Urho3D/Graphics/Skeleton.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Skeleton.pkg
- Source/Urho3D/LuaScript/pkgs/Math/Vector3.pkg
- Source/Urho3D/Math/Vector3.h
- Source/Urho3D/Scene/ValueAnimation.h
> Add some Skeleton and Math helper functions.

- Source/Urho3D/Container/Ptr.h
@weitjong Want to revert some autorefactored things...
> Remove misplace explicits from smart pointers.

- Source/Urho3D/Graphics/RibbonTrail.cpp
- Source/Urho3D/Graphics/RibbonTrail.h
- bin/Data/LuaScripts/45_InverseKinematics.lua
> fix RibbonTrail coverity issues; CID: 127543, 216057, 216060, 216066

- Source/Urho3D/Input/Input.cpp
Pretty bare-bones, does what it says.
Tested OpenGL, D3D9, and D3D11 via the editor. OpenGL is definitely the worst (occasional white void spaces), both DX's repaint about the same and the issues are basically application specific (ie. the editor's lower bar for the window-position setting like to go nuts during layout) - possibly an issue with UI but I didn't look to see how it was positioned as everything else was fine.
The `SDL_SetWindowData(window, "URHO3D_CONTEXT", GetContext());` should probably really go somewhere else as that should probably happen regardless.
> Windows repaint while resizing window.

- Source/ThirdParty/kNet/src/Socket.cpp
I'm using kNet in my multiplayer game, but it often crashes the whole server with SIGPIPE signal. I don't see any point in receiving the signal, so this PR just disables it. The error handling that already exists in the code nicely catches and handles the error.
If you have some information what would be the better way to handle this, please let me know. To my knowledge, this happens in a thread created by the kNet lib, so I don't know if it is possible to somehow catch the signal in the code of my game and ignore it.
I have only tested this on Linux, so I have no idea if it works on Windows or Mac. [Some guy claimed  Windows does not have SIGPIPE](https://stackoverflow.com/questions/23911929/writing-to-a-close-socket-didnt-raise-a-sigpipe-as-expected#comment36851122_23911929), and …
> kNet: Prevent SIGPIPE signal when other end closes connection.

- Source/Urho3D/LuaScript/LuaFunction.cpp
- Source/Urho3D/LuaScript/pkgs/Scene/Scene.pkg
Small fix requested via gitter
> Make LuaFunction::PushLuaTable able to lookup nested tables.

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/RibbonTrail.cpp
- Source/Urho3D/Graphics/RibbonTrail.h
- Source/Urho3D/LuaScript/pkgs/Graphics/RibbonTrail.pkg
Minor enhancement of RibbonTrail. Now it could be used for static objects in moving environment.
Looks working, but I'm not 100% sure.
> Add RibbonTrail base velocity.

- bin/Data/Scripts/Editor/EditorHierarchyWindow.as
Hm, simple smoothed cube has 20 vertices... I think problem in blender exporter
> Editor: more info about models

- Source/Urho3D/Graphics/Direct3D9/D3D9Graphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
PR #2365 only deals with Direct3D 11 so here's another one which also covers OpenGL.
> Log which adapter is used on OpenGL & D3D9

- Source/Urho3D/Math/MathDefs.h
Adds RoundToNearestMultiple to MathDefs.h
> Add RoundToNearestMultiple

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/UI/BorderImage.cpp
- Source/Urho3D/UI/BorderImage.h
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UIBatch.h
Adds material option to BorderImage.
Discussion: https://discourse.urho3d.io/t/custom-ui-mesh-source/4244
> Add UI custom material rendering

- Source/Urho3D/AngelScript/ResourceAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Resource/JSONValue.pkg
- Source/Urho3D/Resource/JSONValue.h
Have never contributed before so please tell me if I should do something differently/made any mistakes as well. I have some more stuff to add as well, just wanna be sure I'm doing this right first.
As for the change, since the GetType methods call IsType to determine if it can get the value of not anyway it makes sense to be able to get a particular default directly.
> Added optional fallbacks to JSONValue GetType methods

- Source/Urho3D/Graphics/CustomGeometry.cpp
- Source/Urho3D/Graphics/CustomGeometry.h
- Source/Urho3D/Math/MathDefs.h
- Source/Urho3D/Math/Matrix3.cpp
- Source/Urho3D/Math/Matrix3.h
- Source/Urho3D/Math/Quaternion.h
- Source/Urho3D/Math/Vector3.h
Okay, I'm doing cleanup here for PR #2476.
I don't want to be "that jerk who just discards other peoples' work", so I'm going to reason my decisions and I'm also giving you guys time to discuss these changes before merge if you have good arguments against this PR. No comments for a week == everybody agrees.
1) `enum AngleType` and related logic is removed completely.
Radians are not used in Urho API. Like, never.
https://urho3d.github.io/documentation/HEAD/_coding_conventions.html
This functionality is against code conventions, so it is to be removed.
`ToRadians` and `ToDegrees` are good on their own, so I kept them.
2) `Matrix3::MakeRotationMatrix` is removed.
There are _a lot_ of issues with this function.
- All the work with Euler angles in Urho is done via Quaternion, so this function …
> Cleanup Math code.

- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
Added a Matrix3x4 overload for Node::SetWorldTransform(), removed some 'both's that referred to three things from the comments.
> Added a Matrix3x4 overload for Node::SetWorldTransform()

- Source/Samples/Utilities2D/Sample2D.cpp
- Source/Samples/Utilities2D/Sample2D.h
- Source/Urho3D/Urho2D/AnimatedSprite2D.cpp
- Source/Urho3D/Urho2D/SpriterData2D.cpp
- Fixed some warnings caused on Sample2D and changed the code to pass structs by reference, instead of by value (when possible)
- Fixed a bug where CharacterMap::Load is always returning false
- Fixed a bug on AnimatedSprite2D animation (alpha animation was not working properly)
> Minor bugs fixed

- CMakeLists.txt
- Docs/GettingStarted.dox
- Docs/Urho3D.dox
- Rakefile
- Source/Clang-Tools/CMakeLists.txt
- Source/ThirdParty/LuaJIT/CMakeLists.txt
- Source/ThirdParty/LuaJIT/src/host/CMakeLists.txt
- Source/ThirdParty/toluapp/src/bin/CMakeLists.txt
- Source/Tools/PackageTool/CMakeLists.txt
- android/launcher-app/CMakeLists.txt
Builds fine with cmake 3.10.2 too.
> Reduced minimum required cmake version to 3.10.2

- bin/Data/PostProcess/Bloom.xml
- bin/Data/PostProcess/BloomHDR.xml
Updated the render target names so the uniforms will work correctly in the shaders.
> Bloom and BloomHDR PostProcess Fix

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Container/FlagSet.h
- Source/Urho3D/Container/Hash.h
- Source/Urho3D/Container/Ptr.h
- Source/Urho3D/Core/WorkQueue.h
- Source/Urho3D/Graphics/Direct3D11/D3D11ShaderVariation.cpp
- Source/Urho3D/Graphics/Viewport.cpp
- Source/Urho3D/Graphics/Viewport.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Viewport.pkg
- Source/Urho3D/Math/Color.cpp
- Source/Urho3D/Math/Color.h
- Source/Urho3D/Math/MathDefs.h
- Source/Urho3D/Math/Matrix2.h
- Source/Urho3D/Math/Matrix3.h
- Source/Urho3D/Math/Matrix3x4.h
- Source/Urho3D/Math/Matrix4.h
- Source/Urho3D/Math/Quaternion.h
- Source/Urho3D/Math/Rect.h
- Source/Urho3D/Math/Vector2.h
- Source/Urho3D/Math/Vector3.h
- Source/Urho3D/Math/Vector4.h
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Resource/Image.h
I don't feel like porting anything big and/or breaking after these heated talks on forums.
So, here are small and simple bits I and others found useful to have that also don't break anything.
I also made a few code quality updates.
* Remove undefined behavior caused by volatile variables in WorkQueue (volatile variables are not required to be thread-safe).
* Fix nasty DX11 bug caused by poor hash functions and likely hash collision in ShaderVariation. Took me hours in VS graphics debugger to catch this one.
* Relaxed FlagSet usage requirements.
* Various API extensions and code simplification.
* Const-correctness fixes (yes, changes in Batch.cpp actually helped).
Hopefully I didn't break the build by accident...
PS. It will be merged in a week if no objections arise.
> Minor API update, bug fixes, cleanup.

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/AngelScript/Urho2DAPI.cpp
Move the AS Drawable2D template definion from source to header
> Allow to make custom class inherited from Drawable2D

- Source/Samples/53_LANDiscovery/LANDiscovery.cpp
- Source/Samples/53_LANDiscovery/LANDiscovery.h
- Source/Urho3D/AngelScript/NetworkAPI.cpp
- Source/Urho3D/Network/NetworkEvents.h
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Urho2D/AnimatedSprite2D.cpp
- Source/Urho3D/Urho2D/CollisionChain2D.cpp
I found a tab and replaced it with spaces.
> Replaced tab with spaces

- bin/Data/LuaScripts/25_Urho2DParticle.lua
- bin/Data/Scripts/25_Urho2DParticle.as
Liberates emitter from screen corner.
> Fixed event data names in AS sample 25

- Source/Urho3D/Network/HttpRequest.cpp
- Source/Urho3D/Network/HttpRequest.h
Otherwise you'll get SSL not initialized error message when making a HTTPS request.
> Initialize SSL when making a HTTP Request and URHO3D_SSL is defined

- Source/Urho3D/UI/Button.cpp
- Source/Urho3D/UI/Button.h
- Source/Urho3D/UI/CheckBox.cpp
- Source/Urho3D/UI/CheckBox.h
- Source/Urho3D/UI/LineEdit.cpp
- Source/Urho3D/UI/LineEdit.h
- Source/Urho3D/UI/Menu.cpp
- Source/Urho3D/UI/Menu.h
- Source/Urho3D/UI/ScrollBar.cpp
- Source/Urho3D/UI/ScrollView.cpp
- Source/Urho3D/UI/Slider.cpp
- Source/Urho3D/UI/Slider.h
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UIElement.cpp
- Source/Urho3D/UI/UIElement.h
- Source/Urho3D/UI/Window.cpp
- Source/Urho3D/UI/Window.h
> Use MouseButtonFlags and QualifierFlags instead of int's

- bin/Data/Materials/PBRTerrain.xml
- bin/Data/Scenes/PBRExample.xml
@1vanK fixed as you suggested.
> PBR sample terrain fixed

- bin/CoreData/Shaders/GLSL/VegetationShadow.glsl
Fix error when compiling vegetation shader and using vsm shadows
> Fix vegetation shader for vsm shadows

- bin/CoreData/Shaders/GLSL/PBRVegetation.glsl
- bin/CoreData/Shaders/GLSL/Vegetation.glsl
- bin/CoreData/Shaders/GLSL/VegetationDepth.glsl
- bin/CoreData/Shaders/GLSL/VegetationShadow.glsl
- bin/CoreData/Shaders/HLSL/PBRVegetation.hlsl
- bin/CoreData/Shaders/HLSL/Vegetation.hlsl
- bin/CoreData/Shaders/HLSL/VegetationDepth.hlsl
- bin/CoreData/Shaders/HLSL/VegetationShadow.hlsl
- bin/CoreData/Techniques/PBR/PBRVegetationDiff.xml
More bugfixes, including one from https://github.com/urho3d/Urho3D/pull/2658
1. VSM shadow support added
2. Model scale and rotation taken into account
> Vegetation shader and technique bugfixes

- bin/CoreData/Shaders/GLSL/PBRLitSolid.glsl
- bin/CoreData/Shaders/GLSL/PBRTerrainBlend.glsl
- bin/CoreData/Shaders/HLSL/PBRLitSolid.hlsl
- bin/CoreData/Shaders/HLSL/PBRTerrainBlend.hlsl
I'm not sure the gamma correction is needed here.
> Remove unused gamma variable

- Source/Urho3D/Math/MathDefs.h
> Fix IsPowerOfTwo(zero).

- Source/Samples/16_Chat/Chat.cpp
- Source/Samples/17_SceneReplication/SceneReplication.cpp
- Source/Samples/17_SceneReplication/SceneReplication.h
- Source/Urho3D/Network/Connection.cpp
- Source/Urho3D/Network/Connection.h
- Source/Urho3D/Network/Network.cpp
- Source/Urho3D/Network/Protocol.h
**Before**
17_SceneReplication server with 3 connected clients
---
**After**
17_SceneReplication server with 3 connected clients
https://github.com/urho3d/Urho3D/issues/2635
> Outgoing messages are now packed together

- Source/Urho3D/Resource/Image.cpp
Missing assignment for alpha channel.
> Fix 3D texture mipmap generator.

- Source/Urho3D/Graphics/Graphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
> Add support of 24-bit depth on mobiles.

- android/urho3d-lib/build.gradle.kts
Add cmake options passed by command line to android build
> gradle add command line options

- bin/Data/Scripts/Editor/EditorSpawn.as
- bin/Data/UI/EditorSpawnWindow.xml
and renamed the option above it to something more accurate
> Added checkbox for editor to parent spawned nodes to selected node

- Source/Urho3D/Audio/Audio.cpp
Limit number of channels to avoid issues on multichannel audio device (5.1, 7.1, etc)
The issue is present on, for example, Logitech G933 headphones with surround sound enabled. 
Bug: https://github.com/urho3d/Urho3D/issues/2718
> Limit number of channels to avoid issues on multichannel audio device

- Source/Samples/15_Navigation/Navigation.cpp
- Source/Samples/39_CrowdNavigation/CrowdNavigation.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UIComponent.cpp
- bin/Data/Scripts/15_Navigation.as
- bin/Data/Scripts/39_CrowdNavigation.as
- bin/Data/Scripts/Editor/EditorGizmo.as
- bin/Data/Scripts/Editor/EditorSecondaryToolbar.as
- bin/Data/Scripts/Editor/EditorToolBar.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/Scripts/Editor/EditorView.as
Should work now, did not tested on Retina though. TODO: `SetFixedXXX` of class `UI` shoube be re-worked.
> Fix UI scale issues.

- Source/ThirdParty/Assimp/code/glTF2Importer.cpp
I noticed glTF2Importer::CanRead not returning the right value on success :wink:
> Fixed GLTF import

- Source/Urho3D/AngelScript/ScriptInstance.h
> Forward declare asITypeInfo to avoid error when including ScriptInstance.h

- Source/Samples/99_Benchmark/AppStateManager.cpp
- Source/Samples/99_Benchmark/AppStateManager.h
- Source/Samples/99_Benchmark/AppState_Base.h
- Source/Samples/99_Benchmark/AppState_Benchmark01.cpp
- Source/Samples/99_Benchmark/AppState_Benchmark01.h
- Source/Samples/99_Benchmark/AppState_Benchmark02.cpp
- Source/Samples/99_Benchmark/AppState_Benchmark02.h
- Source/Samples/99_Benchmark/AppState_Benchmark03.cpp
- Source/Samples/99_Benchmark/AppState_Benchmark03.h
- Source/Samples/99_Benchmark/AppState_MainScreen.cpp
- Source/Samples/99_Benchmark/AppState_MainScreen.h
- Source/Samples/99_Benchmark/AppState_ResultScreen.cpp
- Source/Samples/99_Benchmark/Benchmark02_WomanMover.h
- Source/Samples/99_Benchmark/Benchmark03_MoleculeLogic.cpp
- Source/Samples/99_Benchmark/Benchmark03_MoleculeLogic.h
Huge number of interactions between components
> Bechmark_03

- Source/ThirdParty/SLikeNet/CMakeLists.txt
- Source/Urho3D/Network/Connection.cpp
- Source/Urho3D/Network/Network.cpp
https://github.com/urho3d/Urho3D/issues/2908
> Fix "Mismatched Case in SLikeNet include path"

- Docs/AngelScriptAPI.h
- Docs/ScriptAPI.dox
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/AngelScript/Manual_Container.cpp
- Source/Urho3D/Container/Str.h
String::MIN_CAPACITY is unused after
https://github.com/urho3d/Urho3D/commit/05adc1680bf7783ee5f1c798671fb91042014983
> Remove unused const String::MIN_CAPACITY | Update script doc

- Source/Samples/55_Clicker/CMakeLists.txt
- Source/Samples/55_Clicker/Clicker.cpp
- Source/Samples/55_Clicker/Clicker.h
- Source/Tools/Tests/CMakeLists.txt
- Source/Tools/Tests/Main.cpp
- Source/Tools/Tests/Math/BigInt.cpp
- Source/Urho3D/AngelScript/Generated_Includes.h
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/AngelScript/Generated_ObjectTypes.cpp
- Source/Urho3D/Math/BigInt.cpp
- Source/Urho3D/Math/BigInt.h
Clickers operate on extremely large numbers, so I think that such a class should be exists in the engine (along with an example and bindings). Those who are interested can follow the progress and suggest changes.
> BigInt (WIP)

- Docs/AngelScriptAPI.h
- Docs/ScriptAPI.dox
- Source/Urho3D/AngelScript/Generated_Classes.cpp
- Source/Urho3D/AngelScript/Generated_DefaultConstructors.cpp
- Source/Urho3D/AngelScript/Generated_GlobalFunctions.cpp
- Source/Urho3D/AngelScript/Generated_Includes.h
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/AngelScript/Generated_ObjectTypes.cpp
- Source/Urho3D/Container/Allocator.cpp
- Source/Urho3D/Container/Allocator.h
- Source/Urho3D/Container/HashMap.h
- Source/Urho3D/Container/HashSet.h
- Source/Urho3D/Container/List.h
> Allocator: not bind, replace count type from signed to unsigned

- Docs/AngelScriptAPI.h
- Docs/ScriptAPI.dox
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Container/HashBase.cpp
- Source/Urho3D/Container/HashBase.h
- Source/Urho3D/Container/HashMap.h
- Source/Urho3D/Container/HashSet.h
https://github.com/urho3d/Urho3D/issues/2940
> HashSet, HashMap: use signed type for size

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/UI/LineEdit.cpp
- Source/Urho3D/UI/LineEdit.h
> LineEdit: use signed type

- Source/Urho3D/AngelScript/Generated_GlobalVariables.cpp
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Core/WorkQueue.cpp
- Source/Urho3D/Core/WorkQueue.h
- Source/Urho3D/Graphics/Drawable.h
- Source/Urho3D/Graphics/OcclusionBuffer.cpp
- Source/Urho3D/Graphics/Octree.cpp
- Source/Urho3D/Graphics/View.cpp
- Source/Urho3D/Graphics/View.h
- Source/Urho3D/Urho2D/Renderer2D.cpp
- Source/Urho3D/Urho2D/Renderer2D.h
> WorkQueue: use signed type

- Source/Urho3D/AngelScript/Generated_GlobalVariables.cpp
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Graphics/AnimatedModel.cpp
- Source/Urho3D/Graphics/BillboardSet.cpp
- Source/Urho3D/Graphics/CustomGeometry.cpp
- Source/Urho3D/Graphics/Drawable.cpp
- Source/Urho3D/Graphics/Light.cpp
- Source/Urho3D/Graphics/Octree.cpp
- Source/Urho3D/Graphics/Octree.h
- Source/Urho3D/Graphics/OctreeQuery.h
- Source/Urho3D/Graphics/RibbonTrail.cpp
- Source/Urho3D/Graphics/StaticModel.cpp
- Source/Urho3D/Graphics/StaticModelGroup.cpp
- Source/Urho3D/Graphics/TerrainPatch.cpp
> Octree: use signed type

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Graphics/ParticleEmitter.cpp
- Source/Urho3D/Graphics/ParticleEmitter.h
- Source/Urho3D/UI/ScrollView.cpp
> ParticleEmitter: unsigned to signed

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/UI/ListView.cpp
- Source/Urho3D/UI/ListView.h
- bin/Data/Scripts/Editor/EditorHierarchyWindow.as
- bin/Data/Scripts/Editor/EditorScene.as
- bin/Data/Scripts/Editor/EditorUIElement.as
> ListView: unsigned to int

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/IO/File.cpp
- Source/Urho3D/IO/File.h
- Source/Urho3D/IO/MemoryBuffer.cpp
- Source/Urho3D/IO/MemoryBuffer.h
- Source/Urho3D/IO/NamedPipe.cpp
- Source/Urho3D/IO/NamedPipe.h
- Source/Urho3D/IO/Serializer.h
- Source/Urho3D/IO/VectorBuffer.cpp
- Source/Urho3D/IO/VectorBuffer.h
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
> Node: unsigned to int

- Source/Urho3D/AngelScript/Generated_Classes.cpp
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Resource/XMLElement.cpp
- Source/Urho3D/Resource/XMLElement.h
> XMLElement: unsigned to signed

- CMakeLists.txt
Doesn't print all command line arguments, only options
> Show command line options

- .github/workflows/main.yml
Related: https://github.com/urho3d/Urho3D/issues/3046
> GitHub actions: disable macOS job

- .github/workflows/main.yml
- android/launcher-app/CMakeLists.txt
> Android job: Free up space; do not compile samples

- .github/workflows/main.yml
"git clone" download original repo instead pull request
> Use Checkout action instead "git clone"

- Source/Urho3D/IO/File.cpp
- android/launcher-app/build.gradle.kts
- android/urho3d-lib/build.gradle.kts
https://stackoverflow.com/questions/55571842/android-error-use-of-undeclared-identifier-fseeko
Prepare to [large-file support](https://en.wikipedia.org/wiki/Large-file_support)
> Use 64-bit fseek | Upgrade Android minSdkVersion to 24

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Network/HttpRequest.cpp
- Source/Urho3D/Network/HttpRequest.h
> HttpRequest: unsigned to signed

- Source/Tools/BindingGenerator/ASClassBinder.cpp
- Source/Tools/BindingGenerator/Main.cpp
BindingGenerator is extremely slow in debug configuration
> BindingGenerator: cache derived classes

- Source/ThirdParty/Assimp/CMakeLists.txt
- Source/ThirdParty/Assimp/Urho3DNotes.txt
- Source/ThirdParty/Assimp/code/CMakeLists.txt
- Source/ThirdParty/Assimp/code/ImporterRegistry.cpp
This will make it easier to update the library in the future
> Assimp: restore original code [cache clear]

- Source/Urho3D/AngelScript/ScriptInstance.cpp
> Fixed compile errors when using Urho2D without Physics2D.

- .github/workflows/main.yml
В форке сборка даже не стартует, видимо из-за того, что отключена в апстриме. Вернул без проверки
> GH Actions: Вернул сборку в MacOS

- Source/Urho3D/AngelScript/Manual_Container.cpp
- Source/Urho3D/Container/Str.cpp
- bin/Data/Scripts/Tests.as
- bin/Data/Scripts/Tests/Str/format.as
Add methods for strings formatting in AngelScript.
> Добавил методы для форматирования строк в AngelScript.

- Source/Urho3D/AngelScript/Manual_Core.cpp
Add conversion from unix epoch time to UTC and local time and vice versa for AngelScript.
> Конвертации времени эпохи Unix в локальное и универсальное время и обратно для  AngelScript

- Docs/Reference.dox
- Source/Urho3D/AngelScript/Manual_Container.cpp
- bin/Data/Scripts/Tests/Str/format.as
На ARM64 были баги при извлечении типов параметров, переделал на явное получение.
> AngelScript format string - Fix bugs on 64bit archs.

- Docs/Reference.dox
- Source/Tools/ScriptCompiler/ScriptCompiler.cpp
- Source/Urho3D/AngelScript/Manual_Container.cpp
- Source/Urho3D/AngelScript/ScriptFile.cpp
- Source/Urho3D/AngelScript/ScriptFile.h
Окончательно пофиксил форматирование строк в AngelScript.
Теперь работает и в Web, с general calling conversion.
> Angel script format str

- Source/Urho3D/Core/Context.h
- Source/Urho3D/Math/Frustum.h
Тестовый PR для проверки удаления кэша
> Context.h, Frustum.h: убрал auto [clear cache]
