urho3d/urho3d

- Source/ThirdParty/rapidjson/include/rapidjson/prettywriter.h
- Source/Urho3D/LuaScript/pkgs/Resource/JSONFile.pkg
- Source/Urho3D/LuaScript/pkgs/Resource/XMLFile.pkg
- Source/Urho3D/Resource/JSONFile.cpp
- Source/Urho3D/Resource/JSONFile.h
- Source/Urho3D/Resource/XMLFile.cpp
- Source/Urho3D/Resource/XMLFile.h
- Source/Urho3D/Script/ResourceAPI.cpp
User-configurable indentation for XML and JSON files (AS and Lua bindings included). Closes #591
> User-configurable indentation for XML and JSON files

- Source/Urho3D/Graphics/View.cpp
Fixed a minor compilation error when using the OpenGL renderer.
> Removal of hdrRendering variable caused compilation error when using the OpenGL renderer

- CMake/Modules/Urho3D-CMake-common.cmake
Clang doesn't use include path (-I) when looking for PCH files.  Use full path to header instead.  Tested on Ninja and Make builds using GCC and Clang.
> Fix PCH build with Clang

- Source/ThirdParty/AngelScript/source/as_callfunc_x86.cpp
- Source/ThirdParty/AngelScript/source/as_config.h
Fix for  #708.  Adds a secondary check for recent Clang versions in addition to mingw, so AngelScript won't cause explosions.
> Support MinGW 4.7 ABIs on Clang.

- Source/Urho3D/Navigation/DynamicNavigationMesh.cpp
until open request space is available during obstacle addition/removal.
Pending tile updates may interfere with processing requests.
> Iterate through updating the tilecache

- Source/Samples/08_Decals/Decals.cpp
- Source/Urho3D/Graphics/Geometry.cpp
- Source/Urho3D/Graphics/Geometry.h
- Source/Urho3D/Graphics/OctreeQuery.h
- Source/Urho3D/Graphics/StaticModel.cpp
- Source/Urho3D/LuaScript/pkgs/Graphics/OctreeQuery.pkg
- Source/Urho3D/Math/Ray.cpp
- Source/Urho3D/Math/Ray.h
- Source/Urho3D/Script/GraphicsAPI.cpp
This change adds a new RayQueryLevel - ```RAY_TRIANGLE_UV```
This will ask the query to return texture UV coordinates at Ray-Geometry intersection point.
Since this change is mostly geared towards integrating external UI toolkits, I've only implemented this functionality for StaticModel. _(And frankly doing it for AnimatedModels would be pretty resource intensive)_
This feature will allow us to render UI into textures, place them on the game world objects and properly translate and forward mouse/touch event coordinates to the external UI library.
I've also added a small change to Decals sample to exemplify the usage of this feature.
> Allow ray queries to return UV texture coordinates of ray intersection

- CMake/Modules/Urho3D-CMake-common.cmake
- Docs/GettingStarted.dox
- Docs/Reference.dox
- Source/Urho3D/LuaScript/LuaScript.cpp
- Source/Urho3D/LuaScript/LuaScript.h
* Added `LuaScript::LoadRawFile` and `LuaScript::ExecuteRawFile` to load
files using `luaL_loadfile` rather than via the resource cache
(`luaL_loadbuffer`).  This strategy makes the source available to Lua
debuggers (e.g. eclipse LDT) for setting breakpoints, etc.
* Added a CMake option `URHO3D_LUA_RAW_SCRIPT_LOADER` to make
`luaL_loadfile` the default script loading strategy.
- `LuaScript::ExecuteFile` will thus prefer the `luaL_loadfile`
strategy, aiding in debugging as above, but without needing to change
method calls.
-  `LuaScript::Loader` will also prefer the `luaL_loadfile` strategy,
so that scripts `require`d in the main script are also amenable to
debugging.
- If a script file cannot be loaded from the file system, then it will
fall back on the default resource cache …
> Add `luaL_loadfile` support, with CMake option to prefer this strategy

- Docs/GettingStarted.dox
- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorPreferences.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/Scripts/Editor/EditorView.as
- bin/Data/UI/EditorPreferencesDialog.xml
Some minor tweaks to the editor for more Blender like behavior
- center on selected object using HOME key
- setting for MMB to pan, and use MMB + SHIFT to rotate (currently works the opposite way)
Blender used to be MMB for pan, MMB+SHIFT to rotate for years. Then a couple years ago they switched it around. So the current editor matches fine, but for those of use who (greatly) prefer the original way, that is what this feature is for.
> Jft editor modifications

- Source/Urho3D/Graphics/Direct3D11/D3D11TextureCube.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9TextureCube.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTextureCube.cpp
- Source/Urho3D/LuaScript/pkgs/Resource/Image.pkg
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Resource/Image.h
- Source/Urho3D/Script/ResourceAPI.cpp
- DX10 format support (only data formats compatible, DXT-1/3/5 and RGBA + sRGB variation)
- sRGB flag on Images if indicated by DDS DXGI format
- Images may be "chained" as a list off of the first image (DDS
cubemaps, texture arrays)
- Direct3D9 cubemap loading from DDS standard cubemap
> Expanded DDS support

- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorColorWheel.as
- bin/Data/Scripts/Editor/EditorEventsHandlers.as
- bin/Data/Scripts/Editor/EditorLayers.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/Scripts/Editor/EditorView.as
If you trying to minimize or drag editor window to other desktop(monitor), again minimize or/and resize window, it probably lose handle from EditorView.as on handle ViewMouseMove() also ColorWheel lose their handlers and I guess that LayerEditor also something lose (MouseWheel event to scroll mask types) 
And that why I decide to introduce editor-global-events where all local handlers will be placed.
Please, checkout this.
> global-editor-handlers

- Source/Urho3D/Urho2D/TmxFile2D.cpp
TmxObjectGroup2D::Load was using the presence of the "width" and "height" attributes for deciding whether an object was a rectangle, ellipse or something else. This approach breaks for maps saved in more recent versions of Tiled. This is because the width and height are only saved when they differ from the default (0), and because the width and height are now also used to store the size of tile objects.
So for maps saved with Tiled >= 0.12, this change:
* Fixes identification of rectangle and ellipse objects with 0 width and height (which was leading to the entire map failing to load).
* Fixes identification of tile objects.
> TmxFile2D: Fix determination of object type

- Source/Urho3D/LuaScript/pkgs/ToZerobraneStudioHook.lua
Using the latest version of Zerobrane Studio, I realized that the generated API was not loaded properly.
This PR is what I've used for generating this: https://github.com/pkulchenko/ZeroBranePackage/pull/20
> Fix missing escape characters for the Zerobrane Studio API.

- Source/Urho3D/Script/GraphicsAPI.cpp
- bin/Data/Scripts/Editor.as
- bin/Data/Scripts/Editor/EditorCubeCapture.as
- bin/Data/Scripts/Editor/EditorScene.as
- bin/Data/Scripts/Editor/EditorSettings.as
- bin/Data/Scripts/Editor/EditorUI.as
- bin/Data/Scripts/Editor/EditorView.as
- bin/Data/UI/EditorSettingsDialog.xml
Addition of a command and associated settings for generating cubemaps in the Urho3D editor.
Cubemap sampling is performed at the position of the node containing a selected zone. This is deliberate as node position is considered to be the "true" position of the zone for sampling purposes. For other reasons a zone may need to reach substantially outside of this range (ie. into the sky), even though only a limited area is really relevant for cubemap generation.
During this process existing zones are disabled and duplicates are made matching their traits, this is deliberate to prevent doubling of anything that may depend on the Zone texture.
The added "GetImage" method to Texture2D in script is intended solely for editor usage. It is likely not sufficiently robust for general purpose usage. …
> Add cubemap generation capability to the Urho3D editor

- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLShaderProgram.cpp
- Source/Urho3D/Graphics/ShaderPrecache.cpp
- bin/CoreData/Shaders/GLSL/Transform.glsl
Add support for GPU hardware instancing on Emscripten. In WebGL 1 it is exposed by the ANGLE_instanced_arrays ( https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays/ ) extension, and in WebGL 2, it is enabled in core.
> ANGLE_instanced_arrays

- Source/Urho3D/Core/Timer.cpp
Code duplication cleanup, and use `emscripten_get_now()` when timing, to get sub-millisecond precision timer results (`gettimeofday` calls to JavaScript `Date.now()`, which has only millisecond precision)
> emscripten_get_now()

- Source/Urho3D/Math/Matrix3x4.h
- Source/Urho3D/Math/Matrix4.h
SSE optimize matrix-matrix multiplications when URHO3D_SSE is enabled. These constitute 7.82% of 06_SkeletalAnimation sample with 2000 Jacks in it. After SSE optimizations applied, matrix multiplication takes only 2.13% of total time in AMD CodeXL profile. This change also seems to have the effect that in scalar version, VS2015 did not dare to inline Matrix3x4 multiplication in AnimatedModel::UpdateSkinning(), but after SSE, the instruction count is small enough that it happily does so.
The code uses explicit unaligned loads and stores as opposed to aligned loads, so that memory layout does not need to change.
Only tested on 06_SkeletalAnimation sample, which uses  `Matrix3x4 operator *(const Matrix3x4& rhs)`. It is possible that the other variants are not tested. Tried to carefully check …
> sse_matrix

- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/Graphics/AnimatedModel.cpp
- Source/Urho3D/Graphics/View.cpp
- Source/Urho3D/Graphics/Zone.cpp
- Source/Urho3D/LuaScript/pkgs/Math/BoundingBox.pkg
- Source/Urho3D/Math/BoundingBox.cpp
- Source/Urho3D/Math/BoundingBox.h
- Source/Urho3D/Math/Ray.cpp
- Source/Urho3D/Navigation/NavigationMesh.cpp
- Source/Urho3D/Resource/XMLElement.cpp
- Source/Urho3D/UI/Text3D.cpp
This PR shows how to get rid of the `defined_` boolean in `BoundingBox` class, and instead use `min = INF` and `max = -INF` denote the case when a bounding box is degenerate. This helps reduce branching and SSE'ifying BoundingBox. Using this scheme, it might be possible to further reduce `if (box.Defined())` checks in the codebase, since given how the math falls out, such arithmetic can naturally yield a desired negative result (no hit, outside, etc.) depending on the case.
Also SSE optimizes some hot BoundingBox functions and adds dummy padding floats to `BoundingBox` structure to help SSE loads and stores, which seems safe to do here.
There is also a small (pedantic) logic fix for `BoundingBox::Define(const Vector3* vertices, unsigned count)` when `count == 0`, which should probably …
> no_boundingbox_bool

- Source/Tools/SpritePacker/SpritePacker.cpp
- Source/Urho3D/Urho2D/AnimationSet2D.cpp
- Source/Urho3D/Urho2D/SpriterData2D.cpp
1, When we has only one texture in scml file, the SpriteInfo has wrong x and y values.
2, When we use SpriterPacker without the option "-trim", it will cause wrong frameWidth and frameHeight values
3, The newest version of Spriter use attribute name "object_type" instead of "type"
> fixed the wrong behavior of spriter animation

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/LuaScript/pkgs/Scene/Node.pkg
- Source/Urho3D/Navigation/Obstacle.cpp
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
Despite the branch name (that's what I set out to deal with), there's nothing about detour crowd here.
Changelog:
* Obstacles seek upwards in the scene hierarchy to find their DynamicNavigationMesh rather than downwards from the scene root
* Obstacles now properly clear their ownerMesh_ when scene is cleared/reset, enabling moving them from one scene to another
* Addition of Node::GetParentComponent, Node::GetParentDerivedComponent with script bindings for Angelscript and Lua
> Support navigation obstacle transfer between scenes

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/Drawable.cpp
- Source/Urho3D/Graphics/Drawable.h
- bin/Data/Scripts/Editor/EditorExport.as
- bin/Data/Scripts/Editor/EditorUI.as
Add checkbox options for "Z Axis Up" and "Right handed" to the OBJ exporter. Should cover basically all DCC tools' expectations.
Resolves the mirroring portion of issue #975
> Add Z-up and handedness options to OBJ export

- Source/Samples/Sample.inl
- Source/Urho3D/AngelScript/EngineAPI.cpp
- Source/Urho3D/Engine/DebugHud.cpp
- Source/Urho3D/Engine/DebugHud.h
- Source/Urho3D/IO/FileSystem.cpp
- Source/Urho3D/IO/FileSystem.h
- Source/Urho3D/LuaScript/pkgs/Engine/DebugHud.pkg
- Source/Urho3D/Resource/ResourceCache.cpp
- Source/Urho3D/Resource/ResourceCache.h
- bin/Data/LuaScripts/Utilities/Sample.lua
- bin/Data/Scripts/Utilities/Sample.as
Adds an additional table display that outlines:
* Resource type
* Number resources of that type loaded
* Average resource size
* Largest size of those resource (ie. size of the single biggest texture)
* Budget for that resource type
* Total memory usage for that resource type
Implemented in the samples as F3 key, to toggle on/off.
An image should explain it best:
http://i.imgur.com/pguB10g.png
> ResourceCache memory usage display in DebugHud

- Android/src/org/libsdl/app/SDLActivity.java
Hi,
While testing out the engine's capabilities on Android (which I've found overwhelming - that stuff works better than AAA engines!) I came across an issue - Android hardware keyboard input behaves weird.
And by weird, I mean truly weird.
Tilde (like many other keys, although this one is especially important to me amongst them) calls E_KEYUP and E_KEYDOWN only when no textboxes (such as the LineEdit) are focused, spacebar doesn't even get written in textboxes, enter key randomly defocuses textboxes where on other platforms it doesn't, backspace, while pressed, totally hangs the application where no other key would - and that's probably only a part of the madness.
After a long while of checking where such issue could even be located, and another long while of figuring out what could be …
> Unite Android hardware keyboard input with other platforms

- Source/Urho3D/Graphics/Direct3D11/D3D11Texture.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11Texture.h
- Source/Urho3D/Graphics/Direct3D9/D3D9Texture.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9Texture.h
- Source/Urho3D/Graphics/OpenGL/OGLTexture.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Texture.pkg
Hi,
While testing out the engine on various Android architectures (wanting to support all of them, as the engine is blazingly fast and smaller than it technically should even be), I came across an issue, or rather, the issue came across me - MIPS build doesn't work, random compilation error.
Seeing as that error is *something with graphics*, I've instantly gotten an image of the librarydrivereverythingOpenGL not supporting MIPS before my eyes, and that I won't be able to publish my app to such of an underrated architecture ~~no one even uses~~, thankfully it turned out (much) easier to fix than that - there is a collision between the mips constant used during compilation, and a random variable in the Texture code named the same way.
Having easily fixed it and verified that with the fix …
> Fix Android MIPS build

- Source/Urho3D/Graphics/Drawable.cpp
OBJ export now finds the lowest index of a geometry it's writing to adjust it's written indices against that. Necessary because only the vertices that are actually used by the geometry are written to the file which caused geometries that use index buffer offsets to be very unhappy.
> Fix handling of indices in OBJ export

- Source/Urho3D/Container/Str.cpp
- Source/Urho3D/Container/Str.h
Keeps empty splits by default, optionally omit-able using splitMode parameter - see #1014
> New String::Split implementation

- Source/Urho3D/AngelScript/NavigationAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Navigation/DynamicNavigationMesh.pkg
- Source/Urho3D/Navigation/DynamicNavigationMesh.cpp
- Source/Urho3D/Navigation/DynamicNavigationMesh.h
- Valid range of 3 - 255
- Angelscript + Lua bindings
- Layer maximum changes only effects nav mesh build and does not trigger
a build itself (as with other nav mesh parameters)
Reasoning behind the minimum value of 3 is that layers may occur inside of what the end user would expect to be a "watertight" shape when meshes are stacked on each other. 3 is a reasonably safe lower limit for a scene similar to the 39_CrowdNavigation example.
Default value of 16 is chosen as a reasonably low value that can still cover a "three story building on terrain with extra room for incidental interior layers in solid shapes."
Deals with issue #895
> Add configuration of maximum layers in DynamicNavigationMesh

- Source/ThirdParty/SDL/src/video/x11/SDL_x11modes.c
- Source/ThirdParty/SDL/src/video/x11/SDL_x11sym.h
XRandR support is broken in SDL 2.0.3.  This was fixed in head a few months ago.
https://hg.libsdl.org/SDL/rev/d3fa6d0d3793
https://hg.libsdl.org/SDL/rev/5fa8cf552d05
> Backport XRandR and memory leak fix

- Source/Urho3D/Math/Matrix3x4.h
- Source/Urho3D/Math/Matrix4.h
- Source/Urho3D/Math/Quaternion.h
Work around bug #1053 (https://connect.microsoft.com/VisualStudio/feedback/details/2053175) by replacing the SSE1 specific _mm_ucomige_ss() with SSE2 specific _mm_cvtsi128_si32(_mm_castps_si128(c)) == -1. Given that URHO3D_SSE is targeting SSE2, this workaround has no drawbacks. Closes #1053.
> vs2015_ucomige_ss_workaround

- Source/Urho3D/Math/Matrix3x4.h
Work around VS2010 compiler bug with SSE and copy construction/assignment misalignment. Closes #1044.
> vs2010_sse_alignment_workaround

- Docs/Doxyfile.in
it's common to have an alphabetical class index in the generated documentation. i think it would be helpful here too.
> activated generation of class-index

- Source/Urho3D/Core/ProcessUtils.cpp
Implement GetNumPhysicalCPUs() and GetNumLogicalCPUs() on Emscripten, which calls to emscripten_num_logical_cores() (navigator.hardwareConcurrency API in JS when available, or a guessed "4 cores" when not)
> emscripten_cpu_cores

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/BillboardSet.cpp
- Source/Urho3D/Graphics/BillboardSet.h
- Source/Urho3D/Graphics/Camera.cpp
- Source/Urho3D/Graphics/Camera.h
- Source/Urho3D/Graphics/GraphicsDefs.h
- Source/Urho3D/Graphics/ParticleEffect.cpp
- Source/Urho3D/Graphics/ParticleEffect.h
- Source/Urho3D/Graphics/ParticleEmitter.cpp
- Source/Urho3D/Graphics/Renderer.cpp
- bin/CoreData/Shaders/GLSL/Transform.glsl
- bin/CoreData/Shaders/HLSL/Basic.hlsl
- bin/CoreData/Shaders/HLSL/LitParticle.hlsl
- bin/CoreData/Shaders/HLSL/LitSolid.hlsl
- bin/CoreData/Shaders/HLSL/TerrainBlend.hlsl
- bin/CoreData/Shaders/HLSL/Transform.hlsl
- bin/CoreData/Shaders/HLSL/Unlit.hlsl
- bin/CoreData/Shaders/HLSL/Vegetation.hlsl
- bin/Data/Particle/Burst.xml
- bin/Data/Scripts/Editor/AttributeEditor.as
- bin/Data/Scripts/Editor/EditorParticleEffect.as
- bin/Data/UI/EditorParticleEffectWindow.xml
This pull request will add particle direction inspired by Unity stretched billboard particles. If any of you have tried that on Unity, stretched particle can create pseudo 3d effect despite still using billboard. It can be really useful for sparking effects and many other stuffs. 
Screenshot:
You can see this particle in action at example 'Particle/Burst.xml' or just see this youtube video: https://www.youtube.com/watch?v=zR7KtF6qtaU
About the implementation, I modify the billboard object to store direction. This data only works if new face camera mode FC_DIRECTION is used. If this mode is used, billboard will rotate facing camera with direction as axis, so it will create pseudo 3D effect. Because every billboard has different rotation, Urho needs to calculate rotation for every …
> Direction support for particle/billboard

- Source/Urho3D/Graphics/DebugRenderer.cpp
- Source/Urho3D/Graphics/GraphicsDefs.cpp
- Source/Urho3D/Graphics/GraphicsDefs.h
- Source/Urho3D/Graphics/Renderer.cpp
- Source/Urho3D/Graphics/View.cpp
- bin/CoreData/Shaders/GLSL/Uniforms.glsl
- bin/CoreData/Shaders/HLSL/Uniforms.hlsl
Added a view matrix uniform to the shader code. The impetus for this is to allow me to convert world-space normals into view-space normals to perform SSAO calculations in the rendering pipeline.
> Add view matrix

- Source/Urho3D/Graphics/BillboardSet.cpp
As @weitjong report, there are few Coverity scan bug remains from billboard/particle direction implementation. This is pull request to fix them.
> Fixing some Coverity scan bug on billboard direction implementation

- Source/ThirdParty/SDL/src/video/windows/SDL_windowsevents.c
The error message is:
```
error C2275: 'SDL_Mouse' : illegal use of this type as an expression SDL_windowsevents.c    426    1    SDL
```
This happens because MSVC will compile all ```*.c``` files using the C compiler in C89 mode, meaning all variables must be declared at the beginning of each scope. A change previously made by an Urho3D developer violated this constraint (see diff for more info).
GCC and clang will by default ignore such errors and only generate a warning.
> C89 compliance in SDL_windowsevents.c when compiling under MSVC2012

- bin/Data/Scripts/Editor/EditorUI.as
This fix just solve the problem with typing text into current active UIText element
- with ~ z, 1,3,4... keys.
- this issue exist only in blender mode keys
> fix-for-ui-typing-in-b.mode

- Source/Urho3D/Container/Ptr.h
- Source/Urho3D/Graphics/Renderer.cpp
Cannot see any reason to avoid implicit upcasting of SharedPtr.
This allows not to use `StaticCast` where silent upcasting is possible.
Besides I have changed comparision operators to allow mixed comparisions.
Some testing was performed.
This is my first pull request to test Urho3D collaboration :) so hello everyone!
> Allow implicit conversions of SharedPtr objects.

- Source/Urho3D/Graphics/Animation.h
I was trying to add procedurally generation animation tracks but was getting the error ```undefined reference to``` whenever I tried using member functions of ```AnimationTrack```.
> Exposing AnimationTrack class as part of the public API

- Source/ThirdParty/SDL/src/video/wayland/SDL_waylanddyn.h
- Source/ThirdParty/SDL/src/video/wayland/SDL_waylandsym.h
Applied patch to fix undefined reference error when compiling for Wayland (1.10) on Linux.
This has been fixed in SDL, but no SDL release has been made that includes this fix.
The SDL fix can be found here:
https://hg.libsdl.org/SDL/rev/330f500d5815
In the mean time, this fixes Urho3D compilation on Linux.
```
[ 74%] Linking CXX executable ../../../bin/Urho3DPlayer
../../../lib/libUrho3D.a(SDL_waylandvideo.c.o): In function `display_handle_global':
SDL_waylandvideo.c:(.text+0x593): undefined reference to `wl_proxy_marshal_constructor_versioned'
SDL_waylandvideo.c:(.text+0x5d4): undefined reference to `wl_proxy_marshal_constructor_versioned'
SDL_waylandvideo.c:(.text+0x61d): undefined reference to `wl_proxy_marshal_constructor_versioned'
SDL_waylandvideo.c:(.text+0x684): undefined …
```
> Applied patch to fix undefined reference error when compiling for Wayland on Linux.

- Source/Urho3D/Core/Object.cpp
- Source/Urho3D/Core/Object.h
And removed redundant EventHandler() constructor adding default value 0 for `userData`. Less code, does exactly the same. If there was good reason for two constructors to exist please let me know, ill be happy to fix PR in case this is unwanted change.
Now it is possible to:
SubscribeToEvent(..., [&](StringHash type, VariantMap& args) {
// win
});
void Class::SomeEventHandler(StringHash type, VariantMap& args)
{
}
SubscribeToEvent(..., std::bind(&Class::SomeEventHandler, this)));
void Class::SomeOtherEventHandler(VariantMap& args)
{
}
SubscribeToEvent(..., std::bind(&Class::SomeOtherEventHandler, this, _2)));
There is an ugly workaround - `EventHandler` asserts that `receiver_` is not `0`. This is not relevant in case of c++11 as receiver is captured by `std::function<>` therefore i set …
> C++11 event binding (lambdas/std::bind).

- Source/Urho3D/Graphics/Material.cpp
Changed the conditions when unsubscribes the shader animation events.
Or it will unsubcribe all the events if you call SetShaderParameterAnimation function twice. (For example, you need to animate texture U and V )
> Shader animation bug.

- Source/Urho3D/AngelScript/ScriptFile.cpp
I noticed that some variant types that have objects exposed to the AngelScript subsystem are not captured as type of parameters that can be passed when calling an AngelScript function from C++. This implementation rectifies it.
> Add additional Variant Types For ScriptInstance::Execute()

- Source/Urho3D/LuaScript/pkgs/UI/ScrollBar.pkg
- Source/Urho3D/UI/ScrollBar.cpp
- Source/Urho3D/UI/ScrollBar.h
Allow set background for ScrollBar
Old:
New:
```
listView->GetVerticalScrollBar()->SetColor(Color(1.0f, 1.0f, 1.0f, 1.0f));
listView->GetVerticalScrollBar()->SetStyle("ScrollBar");
listView->GetVerticalScrollBar()->GetSlider()->SetColor(Color(0.0f, 0.0f, 0.0f, 0.0f));
```
> ScrollBar base class from UIElement to BorderImage

- Source/Urho3D/AngelScript/Urho2DAPI.cpp
- Source/Urho3D/Urho2D/TileMap2D.cpp
- Source/Urho3D/Urho2D/TileMapDefs2D.cpp
- Source/Urho3D/Urho2D/TileMapDefs2D.h
- Source/Urho3D/Urho2D/TmxFile2D.cpp
This patch implements hexagonal type of 2D Map, so that it provides possibility to work with the hexagonal maps from Tiled Map Editor.
> Add O_HEXAGONAL type of 2D Map

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/Batch.cpp
- Source/Urho3D/Graphics/Batch.h
- Source/Urho3D/Graphics/Drawable.cpp
- Source/Urho3D/Graphics/Drawable.h
- Source/Urho3D/Graphics/Renderer.cpp
- Source/Urho3D/Graphics/Renderer.h
- Source/Urho3D/Graphics/View.cpp
- Source/Urho3D/LuaScript/pkgs/Graphics/Renderer.pkg
- Source/Urho3D/Math/StringHash.h
Hi all.
These changes allow to set custom per-instance data in SourceBatch and implement things like smooth LOD switch.
https://github.com/urho3d/Urho3D/issues/1405
For now it it internal feature that can be used from Drawable derived-s.
So it is impossible to set these data from external code with public methods.
I just don't need such use case and have no ideas about good interface for it.
It could be settable property of `Drawable` like `Vector4 instancingData_[MAX]`, as suggested by **cadaver**, or something else.
I am not sure how much MAX should be. Now it is 4. I suppose it is enough for most cases. Is it enough? Is it okay to add extra 64 bytes for each drawable?
Where can I place this constant? Is `GraphicDefs.h` good place?
Custom per-instance data also does not work without …
> Add support of custom per-instance data in batches.

- Source/Samples/44_RibbonTrailDemo/RibbonTrailDemo.cpp
- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/RibbonTrail.cpp
- Source/Urho3D/Graphics/RibbonTrail.h
- Source/Urho3D/LuaScript/pkgs/Graphics/RibbonTrail.pkg
- bin/Data/LuaScripts/44_RibbonTrailDemo.lua
- bin/Data/Scripts/44_RibbonTrailDemo.as
I'm adding update invisible parameter to Ribbon Trail so node can still emit trail even if it isn't visible to the camera. The default is off for optimization, but all trail on the samples are using it.
> Add update invisible parameter to RibbonTrail.

- Source/Urho3D/Graphics/View.h
Change View::FindNamedTexture() function to be public for convenience
> Change View::FindNamedTexture() function to be public

- Source/Urho3D/Graphics/GraphicsEvents.h
- Source/Urho3D/Graphics/RenderPath.cpp
- Source/Urho3D/Graphics/RenderPath.h
- Source/Urho3D/Graphics/View.cpp
A new "sendevent" render path command can now be added. This render path command will send an E_RENDERPATHEVENT event with the specified name. This can be used to execute some code at a specific point during the rendering.
_<command type="sendevent" name="MyCustomName"/>_
Feel free to suggest me some changes to the names that i have used. Since English is not my native language some names may not be nice :)
> SendEvent new renderpath command

- Source/Urho3D/Graphics/BillboardSet.cpp
- bin/CoreData/Shaders/GLSL/Transform.glsl
- bin/CoreData/Shaders/HLSL/Basic.hlsl
- bin/CoreData/Shaders/HLSL/LitParticle.hlsl
- bin/CoreData/Shaders/HLSL/LitSolid.hlsl
- bin/CoreData/Shaders/HLSL/PBRLitSolid.hlsl
- bin/CoreData/Shaders/HLSL/TerrainBlend.hlsl
- bin/CoreData/Shaders/HLSL/Transform.hlsl
- bin/CoreData/Shaders/HLSL/Unlit.hlsl
- bin/CoreData/Shaders/HLSL/Vegetation.hlsl
After developing RibbonTrail feature, I realized it's no longer need to passing camera position to direction billboard vertex buffer because Urho3D already has default uniform to do the job.
> Optimize direction billboard vertex buffer

- Source/Urho3D/IO/Deserializer.cpp
- Source/Urho3D/IO/Deserializer.h
- Source/Urho3D/IO/Serializer.cpp
- Source/Urho3D/IO/Serializer.h
Because int are not always sufficient, support 64b values to Serialisation interface
> Add int64_t and uint64_t support for Serializer/Deserializer

- Source/Urho3D/Physics/CollisionShape.cpp
- Source/Urho3D/Physics/CollisionShape.h
- Source/Urho3D/Physics/PhysicsWorld.cpp
- Source/Urho3D/Physics/PhysicsWorld.h
* Add static `config` variable to `PhysicsWorld`, allowing overrides to be set prior to construction - currently just for the `btCollisionConfiguration`.
* Add protected member function to `CollisionShape` to allow for configuring custom collision shapes.
Example usage (from my own code):
Somewhere before creating the physics component
```
PhysicsWorld::config.collisionConfig = new btFeltCollisionConfiguration();
```
I can then use my override of the collision configuration to deal with my custom shape
```
btCollisionAlgorithmCreateFunc* btFeltCollisionConfiguration::getCollisionAlgorithmCreateFunc(
int proxyType0, int proxyType1
) {
if (btBroadphaseProxy::isConvex(proxyType0) && (proxyType1 == CUSTOM_CONCAVE_SHAPE_TYPE))
{
return m_convexSurfaceCF;
}
if …
```
> Alllow override of internal physics configuration and custom collision shapes

- Source/Urho3D/AngelScript/ResourceAPI.cpp
Really simple fix to allow scripts to use JSONValue.size property.
> Made JSONValue.get_size() const

- Docs/Reference.dox
- README.md
- Source/Urho3D/Input/Input.cpp
- Source/Urho3D/Input/InputEvents.h
Added three input-related events:
* E_INPUTBEGIN : input handling starts.
* E_INPUTEND : input handling ends.
* E_SDLRAWINPUT : raw SDL event is sent for customized event processing.
`E_SDLRAWINPUT` additionally checks `P_CONSUMED` value (which is `false` by default) and if it is set to true event is discarded. This is for libraries that would like to take over input handling completely.
Need for other two events arose from handling nuklear UI events. It requires to do some things before and after input handling. Without these events doing those tasks took bit of improper hackery abusing other events and their order which is not good at all.
> Input events

- Docs/Urho3D.dox
The current history (v1.6 right before release) has the below line
> AngelScript support on also on Emscripten and 64-bit iOS, based on generic bindings
corrected to 
> AngelScript support on Emscripten and 64-bit iOS, based on generic bindings
> Minor Typo correction

- Source/Urho3D/Scene/Serializable.h
This PR introduces three new macros URHO3D_ACCESSOR_ATTRIBUTE_FREE, URHO3D_ENUM_ACCESSOR_ATTRIBUTE_FREE and URHO3D_MIXED_ACCESSOR_ATTRIBUTE_FREE, that work exactly as their counterparts except that they receive free function pointers instead of member ones.
You could ask: 'Why do you need such strange case??'
However, I found this case useful because it allows to write lambda's just inside macros and don't bloat class public interface. Maybe there are some other cases, but this one is primary for me. These changes shouldn't disturb anything, so I have made PR.
**Update: Damn, I miscopypasted something..**
> Add support of free functions as attribute accessors.

- Source/Urho3D/Container/Vector.h
Related to #1556.
I re-organized vector code to prevent old buffer destruction in case of reallocation until new buffer is constructed. I also removed this hacky macro and added one new ctor for both vectors.
**Upd:** I smoke-tested Editor and all demos.
> Refactor Vector and PODVector implementation.

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Graphics/BillboardSet.cpp
- Source/Urho3D/Graphics/BillboardSet.h
- Source/Urho3D/Graphics/Camera.cpp
- Source/Urho3D/Graphics/Camera.h
- Source/Urho3D/Graphics/GraphicsDefs.h
- Source/Urho3D/LuaScript/pkgs/Graphics/BillboardSet.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/GraphicsDefs.pkg
- Source/Urho3D/LuaScript/pkgs/UI/Text3D.pkg
- Source/Urho3D/UI/Text3D.cpp
- Source/Urho3D/UI/Text3D.h
This PR is a small improvement of Urho's billboard system.
**LookAt Y** and **Rotate Y** modes are useful for rendering some grounded objects like grass or trees that shouldn't be freely rotated. Such billboards degrade when camera looks downside and this case is often unwanted.
This PR introduces new mode called **LookAt Mixed** that is a hybrid of **LookAt XYZ** and **LookAt Y**. New attribute **minAngle** controls minimum angle between billboard normal and look-at direction. 0 is **LookAt Y** mode, 90 is **LookAt XYZ**. Small values of **minAngle** allow user to have almost-lookat-Y billboards that don't degrade when looking downside. See screenshot.
Unfortunatelly, implementation for **Rotate Y**/**Rotate XYZ** looks much more difficult. But maybe it will be implemented at some point.
> Add new face camera mode to BillboardSet and Text3D.

- bin/CoreData/Shaders/GLSL/Skydome.glsl
in my mac, skydome is not shown and output an error:
ERROR: Failed to compile vertex shader Skydome():
ERROR: 0:516: Identifier name 'gl_ModelViewMatrix' cannot start with 'gl_'
ERROR: 0:517: Identifier name 'gl_ProjectionMatrix' cannot start with 'gl_'
[Sun Sep 11 13:05:23 2016] ERROR: Failed to compile pixel shader Skydome():
ERROR: 0:516: Identifier name 'gl_ModelViewMatrix' cannot start with 'gl_'
ERROR: 0:517: Identifier name 'gl_ProjectionMatrix' cannot start with 'gl_'
> fix skydome glsl error

- Source/Urho3D/Graphics/Camera.cpp
Mixed mode needs true look-at vector instead of XZ projection.
Recent refectoring changed this: https://github.com/urho3d/Urho3D/commit/d19d8d3dbfd962cce273bf43dadaa32bb08bcab8
PS: Yes, I _do_ like const-s and I will write'em wherever possible. Because they avoid errors like this one.
> Fix LookAt Mixed rotation mode.

- Source/Urho3D/AngelScript/Addons.cpp
RefCastObject adds one ref by itself. So extra AddRefScriptObject call cause memory leak when Dictionary.Get is called from script.
I'm not 100% sure in this solution. However, I've smoke-tested Editor and my project - no crashes, no leaks.
Closes #1582
> Fix memory leak in Dictionary.

- Source/Urho3D/Input/Input.h
`Input::SetMousePosition()` and `Input::CenterMousePosition()` are moved to public access scope to allow access to these APIs. Sometimes there is need to manually position cursor and there are no other means.
One of such usecases is  having cursor hover UI button when application is opened should button be positioned right in center of the screen. This is more of a problem on mobile platforms where cursor is not visible and it is not clear why one (hovered) button looks differently than the others.
> Expose mouse position manipulation api in Input class

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Container/Ptr.h
- Source/Urho3D/Graphics/Texture2D.cpp
- Source/Urho3D/Graphics/Texture2D.h
- Source/Urho3D/Graphics/TextureCube.cpp
- Source/Urho3D/Graphics/TextureCube.h
- Source/Urho3D/LuaScript/pkgs/Graphics/Animation.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/Material.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/Model.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/ParticleEffect.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/RenderPath.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/Texture2D.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/TextureCube.pkg
- Source/Urho3D/LuaScript/pkgs/Network/Network.pkg
- Source/Urho3D/LuaScript/pkgs/Resource/ResourceCache.pkg
- Source/Urho3D/LuaScript/pkgs/UI/UI.pkg
- Source/Urho3D/LuaScript/pkgs/Urho2D/ParticleEffect2D.pkg
I needed Texture2D::GetImage for last months and today I've found out that Urho already has such function in AS binding. So I've moved it to C++ class and updated Lua pkgs. I've also added some error messages and simplified some Lua bindings around Detach.
> Move Texture2D::GetImage and TextureCube::GetImage implementations.

- Source/Urho3D/Database/SQLite/SQLiteConnection.cpp
This should allow sql queries to run properly when DbConnection::Execute is provided a string. This fix is only for SQLite queries.
> Fixed an issue for SQLite queries where String::Trimmed was being corrupted

- Source/Urho3D/Engine/Console.cpp
Not saving repetitive lines since it's redundant and makes it longer to navigate to not-the-same previous lines.
> Don't save line repetitions in the console's history

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/Graphics/Terrain.cpp
- Source/Urho3D/LuaScript/pkgs/Scene/Node.pkg
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
- Source/Urho3D/Urho2D/TileMap2D.cpp
- Source/Urho3D/Urho2D/TileMapLayer2D.cpp
- bin/Data/Scripts/Editor/EditorHierarchyWindow.as
Related to #1664 
I'ven't managed to fix bottleneck in Hierarchy View. However, I've optimized temorary nodes and how Editor deal with them. Since procedural nodes like terrain pathces are temporary, these changes are pretty good workaround for my issue.
Please, review changes in **EditorHierarchyWindow.as** for possible unwanted side effects.
> Optimize Editor work with temporary objects

- Source/Urho3D/Scene/Serializable.h
Various calls to GetVariantType are missing a using namespace.
As such, when a project doesn't have the line ```using namespace Urho3D``` (such as my own ^^), a compile error will be generated regarding the use of GetVariantType.
This fixes that.
> Added namespace prefix for various calls to GetVariantType

- Source/Urho3D/Graphics/Terrain.cpp
- Source/Urho3D/Graphics/Terrain.h
- Missing include added.
- Terrain UV coordinates fixed.
The image below shows how UV coordinates currently go in the place where one Terrain object changes to another. This PR fixes it.
> Fix minor Terrain bugs.

- Source/Urho3D/AngelScript/CoreAPI.cpp
- Source/Urho3D/AngelScript/SceneAPI.cpp
- Source/Urho3D/Core/Attribute.h
- Source/Urho3D/Graphics/AnimatedModel.cpp
- Source/Urho3D/Graphics/BillboardSet.cpp
- Source/Urho3D/Graphics/StaticModelGroup.cpp
- Source/Urho3D/Navigation/CrowdManager.cpp
- Source/Urho3D/Scene/Serializable.h
- Source/Urho3D/Scene/SplinePath.cpp
- bin/Data/Scripts/Editor/AttributeEditor.as
See issue #1741 .
Now variant vector structs elements names can be defined from AttributeInfos. Now AnimatedModel, CrowdManager, SplinePath, BilboardSet and StaticModelGroup use this way to do it.
> Allow define of variant vector structs attributes

- Source/Urho3D/CMakeLists.txt
I have run into issue with MRI script special characters when building inside my "projects/c++/" directory.
Seems like not only spaces are problematic and no escaping is available.
https://sourceware.org/binutils/docs/binutils/ar-scripts.html
> The syntax for the ar command language is straightforward:
...
>     comments are allowed; text after either of the characters `*' or `;' is ignored.
...
>     Whenever you use a list of names as part of the argument to an ar command, you can separate the individual names with either commas or blanks. Commas are shown in the explanations below, for clarity.
...
>     `+' is used as a line continuation character; if `+' appears at the end of a line, the text on the following line is considered part of the current command. 
In case I understand it …
> Avoid special chars in paths in MRI script passed to ar utility

- bin/CoreData/Shaders/GLSL/Text.glsl
- bin/CoreData/Shaders/HLSL/Text.hlsl
Only GL version currently. Supersampling can be disabled by comment define.
SDF rendering improved even without using supersampling (dynamic calculation of border width + smoothstep for outline). But outlines and shadows still dirty for far distance. Any notes?
> SDF supersampling

- Source/Urho3D/Urho2D/StaticSprite2D.cpp
- Source/Urho3D/Urho2D/StaticSprite2D.h
Hello, here is a fix for the following case :
* Create a node without a scene
* Add TileMap2D component
* call SetTmxFile(...)
This was crashing because 'renderer_' was null in StaticSprite2D.
Now it won't crash and StaticSprite2D will update its material when added to a scene.
> Fix crash related to TileMap2D when no scene is set

- Source/Urho3D/Audio/Audio.cpp
- Source/Urho3D/Core/Context.cpp
- Source/Urho3D/Core/Context.h
- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9Graphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
- Source/Urho3D/Input/Input.cpp
```SDL_Init()``` and ```SDL_Quit()``` are now located in the ```Context``` class. Urho3D subsystems can use ```context_->RequireSDL(SDL_INIT_SUBSYSTEM);``` and ```context_->ReleaseSDL()``` in their constructor/destructors if they require the use of SDL functions. The ```Context``` class globally keeps track of the number of calls to ```RequireSDL()``` so it knows when to call ```SDL_Quit()```
> fixes #1781 - Moved SDL_Init() into Context class

- Source/Tools/RampGenerator/RampGenerator.cpp
Adds Gobo/Cookie baking from IES files to RampGenerator.
Part of a series of PRs I'll submit for old functionality I'd like to see merged in.
**Note:** I couldn't figure out how to filter these based purely on the data, the blur could be removed if someone else can sort out this lat/lon ray thing better, I never found a method that dealt with it robustly enough (bollard lights break everything). Blurring is generally sufficient.
I'll be opening a series of issues, they won't be actual issues but more matters of serious discussion regarding merging such as OpenCL, Texture cube arrays, geom/hull/dom shaders, etc.
> JS: Add IES cookie generation to RampGenerator

- bin/Data/Scripts/Editor/EditorView.as
Currently Physics2D debug is visible only when PhysicsWorld2D component is selected, so is hard to tuning Shape2D size
> Editor: F3 also toggle Physics2D debug geometry

- Source/Urho3D/IO/AbstractFile.h
- Source/Urho3D/IO/File.h
- Source/Urho3D/IO/MemoryBuffer.cpp
- Source/Urho3D/IO/MemoryBuffer.h
- Source/Urho3D/IO/NamedPipe.h
- Source/Urho3D/IO/VectorBuffer.h
Added AbstractFile class. It is used as parent class for classes that implement both Serializer and Deserialized.
While doing profiler work i found a need to interact with objects that implement both `Serializer` and `Deserializer`. Urho3D has several such objects but all of them inherit both classes separately. That means there is no way to have type system require an object implementing both. For this reason `AbstractFile` class was created and objects that inherited both `Serializer` and `Deserializer` now inherit `AbstractFile` instead.
> AbstractFile class

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/Container/Vector.h
- Source/Urho3D/Engine/Engine.cpp
- Source/Urho3D/Engine/Engine.h
- Source/Urho3D/LuaScript/pkgs/Scene/Node.pkg
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
Main change here is in 4th commit of this PR.
I wanted to allow change paths on-the-fly with the same semantic as they are initialized.
I intentionally didn't add force ResourceCache force cleanup because it can be easlily done outside.
@cadaver, please check for important things that I may have missed.
**Note for reviewers**: it's easier to review changes in Engine.cpp via https://github.com/urho3d/Urho3D/pull/1832/commits/f386678667396b342bc40a9ba9a52154914452e3
> Extract some code to increase reusability.

- Source/Urho3D/UI/Slider.cpp
Slider has a feature where setting min and max size of knob allows us to control it's size. However when knob size is enlarged moving know causes it to jump forward and back. This change fixes the issue.
> Fix jumping slider knob when it's size is fixed.

- Source/Urho3D/AngelScript/ResourceAPI.cpp
Bind [ResourceCache::GetResources](https://urho3d.github.io/documentation/1.6/class_urho3_d_1_1_resource_cache.html#ada668dffb5057808c40306ffc26ff6d2) to AngelScript (this function was missed).
> Bind ResourceCache::GetResources.

- Source/Urho3D/Core/Thread.cpp
When URHO3D_THREADING is not defined, Thread::GetCurrentThreadID() was missing a return statement. Also the helpers for invoking a thread should be static, which will hide their symbols.
> Fix Thread::GetCurrentThreadID() if threading is disabled.

- Source/Urho3D/Urho2D/PhysicsEvents2D.h
- Source/Urho3D/Urho2D/PhysicsWorld2D.cpp
- Source/Urho3D/Urho2D/PhysicsWorld2D.h
- Added serialized contact info for each physical2D event;
+ Temporary pre-allocated buffer inside PhysicsWorld2D is used, so it shan't be heavy;
+ New parameter is called `ContactPoints` and similar to `Contacts` parameter of physical events;
+ I wanted to call new parameter `Contacts` too, but it can be easily mixed up with already existing `Contact` parameter. May be discussed.
- Added event for contact update.
+ Similar to `NodeCollision` event, called from Box2D internals while contact is on between pre-step and post-step;
+ Can be used for simple check of ongoing contact in script logic;
+ Contact may be disabled in event handler;
+ Can be used for creating simple one-way obstacles and so on.
- By default Box2D re-enable contact before each check. I disabled this behavior because I …
> Improve Box2D integration

- Source/Urho3D/Urho2D/ParticleEffect2D.cpp
The 2D particles had missing blend mode functions for
BlendMode::BLEND_SUBTRACT and BLEND_SUBTRACTALPHA. The values for the
functions have been copied from OGLGraphics.cpp.
If C++11 is enabled, the size of the struct is checked with a static
assertion, now.
> Fixed blend modes for 2D particles

- Source/Urho3D/Resource/JSONFile.cpp
When converting JSONValue to rapidsjon::Value, create the array elements and
object properties fully before adding them to rapidjson. This makes the
whole operation more efficient because it avoids a useless lookup on the
newly created/added elements.
> Populate a newly created rapidjson-value before adding it to the parent.

- Source/Urho3D/AngelScript/IKAPI.cpp
- Source/Urho3D/Core/Context.cpp
Is the sample 45_InverseKinematics supposed to fail compilation if you set URHO3D_IK=OFF? I don't see any header guards around the physics samples (though I haven't tried compiling the physics samples with URHO3D_PHYSICS=OFF).
> fixes #1907 - Compiler error when URHO3D_IK=OFF

- Source/Tools/PackageTool/PackageTool.cpp
We have found and fixed a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/
We suggests having a look at the emails, sent from @pvs-studio.com.
Analyzer warning: [V693](https://www.viva64.com/en/w/V693/) Consider inspecting conditional expression of the loop. It is possible that 'i < X.size()' should be used instead of 'X.size()'. PackageTool.cpp 148
> PackageTool.cpp: PVS-Studio: fixed conditional expression of the loop.

- Source/Urho3D/IK/IKSolver.cpp
We have found and fixed a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/
We suggests having a look at the emails, sent from @pvs-studio.com.
Analyzer warning: [V591](https://www.viva64.com/en/w/V591/) Non-void function should return a value. IKSolver.cpp 57
> IKSolver.spp: PVS-Studio: Non-void function should return a value

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/AngelScript/AudioAPI.cpp
- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/Audio/Sound.cpp
- Source/Urho3D/Audio/Sound.h
- Source/Urho3D/Graphics/Animation.cpp
- Source/Urho3D/Graphics/Animation.h
- Source/Urho3D/Graphics/Texture.cpp
- Source/Urho3D/Graphics/Texture.h
- Source/Urho3D/LuaScript/pkgs/Audio/Sound.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/Animation.pkg
- Source/Urho3D/LuaScript/pkgs/Graphics/Texture.pkg
- Source/Urho3D/LuaScript/pkgs/Resource/Resource.pkg
- Source/Urho3D/Resource/Resource.cpp
- Source/Urho3D/Resource/Resource.h
I found it useful.
Please, review. Discussion about naming is open.
It would be great to have such ability for all binary resources, but I don't know nice way to implement it.
Example:
```
Animation@ anim = cache.GetResource("Animation", "Animations/Kachujin_Idle.ani");
Print(anim.metadata["speed"].GetFloat());
anim.metadata["dir"] = Variant(Vector3(1, 1, 1));
Array<Variant> vec;
vec.Push(Variant("String"));
vec.Push(Variant(10));
vec.Push(Variant(15.0));
anim.metadata["vec"] = Variant(vec);
anim.Save(cache.resourceDirs[0] + anim.name);
```
> Add support of arbitrary data in Sound, Animation and Texture resources.

- Source/Urho3D/Math/MathDefs.h
- Source/Urho3D/Math/Vector3.h
Useful for creating hashed adjacency lists for navigation meshes.
> Hash code calculation for Vector3

- Source/Urho3D/Graphics/VertexBuffer.cpp
- Source/Urho3D/Graphics/VertexBuffer.h
I noticed VertexBuffer has many static functions to handle `PODVector<VertexElement> elements` that are outside VertexBuffer. However, it is missing a static function to update offsets of elements, so static `VertexBuffer::GetElementOffset()` does not work in certain situations. This PR adds a new static function that user can manually call to calculate offsets.
I tested it in one of my projects and it seems to work.
Another option would be to not use precalculated values, and do more manual work in static `VertexBuffer::GetElementOffset()`.
> Static VertexBuffer::UpdateOffsets()

- Source/Urho3D/UI/FontFaceFreeType.cpp
- Source/Urho3D/UI/FontFaceFreeType.h
Closes #1976
FontFaceFreeType checks at runtime whether the whole font can be loaded
into a single texture, by preflighting all the necessary texture atlas
placements in CanLoadAllGlyphs.
However, this preflight operation was slightly different from the real
texture atlas generation, so sometimes CanLoadAllGlyphs was incorrectly
returning true. The LoadCharGlyph would then switch to a new texture
atlas (via SetupNextTexture). This would usually make Text elements
vanish, as the rendered glyphs were in the wrong texture.
We fix this bug with two changes:
- Make CanLoadAllGlyphs process the same char codes in the same order
- Make CanLoadAllGlyphs skip zero-size glyphs (as LoadCharGlyph does)
We also log an error if SetupNextTexture is called unexpectedly, to
help catch future occurrences.
> Fix bug in FontFaceFreeType::CanLoadAllGlyphs that can make text vanish

- Source/Samples/47_Typography/CMakeLists.txt
- Source/Samples/47_Typography/Typography.cpp
- Source/Samples/47_Typography/Typography.h
- bin/Data/LuaScripts/47_Typography.lua
- bin/Data/Scripts/47_Typography.as
Displays text in various sizes, with checkboxes to play with settings that affect the way text is rendered:
- Color (white-on-black versus black-on-white)
- Autohinter
- SRGB output conversion (not available on all platforms)
> Add a 'Typography' sample program

- Source/Samples/47_Typography/Typography.cpp
- Source/Samples/47_Typography/Typography.h
- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/UI.pkg
- Source/Urho3D/UI/FontFaceFreeType.cpp
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UI.h
- bin/Data/LuaScripts/47_Typography.lua
- bin/Data/Scripts/47_Typography.as
There are three levels: NORMAL (the default), LIGHT and NONE.
The LIGHT level makes FreeType align font outlines to pixel
boundaries vertically, but not horizontally.
This is needed for #1953, as subpixel character positioning doesn't make sense with fully-hinted glyphs -- the whole point of hinting is to align glyphs to the pixel grid.
> Add UI.FontHintLevel property

- Source/Samples/47_Typography/Typography.cpp
- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/Text.pkg
- Source/Urho3D/LuaScript/pkgs/UI/Text3D.pkg
- Source/Urho3D/UI/Font.cpp
- Source/Urho3D/UI/Font.h
- Source/Urho3D/UI/FontFace.h
- Source/Urho3D/UI/FontFaceBitmap.cpp
- Source/Urho3D/UI/FontFaceBitmap.h
- Source/Urho3D/UI/FontFaceFreeType.cpp
- Source/Urho3D/UI/FontFaceFreeType.h
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/Text.h
- Source/Urho3D/UI/Text3D.cpp
- Source/Urho3D/UI/Text3D.h
- bin/Data/LuaScripts/47_Typography.lua
- bin/Data/Scripts/47_Typography.as
This commit changes the 'pointSize' parameter in Font, Text
and Text3D from an int to a float, allowing e.g. 14.5pt text.
Note that when hinting is enabled, font metrics are snapped
to pixel boundaries, so the effect may be hard to see unless
you also set UI.FontHintLevel to LIGHT or NONE.
This is a change to the public API, but existing code (including
scripts) should compile and run as before.
> Change font size to a float (closes #1952)

- Source/Samples/47_Typography/Typography.cpp
- Source/Samples/47_Typography/Typography.h
- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/Font.pkg
- Source/Urho3D/LuaScript/pkgs/UI/Text.pkg
- Source/Urho3D/LuaScript/pkgs/UI/Text3D.pkg
- Source/Urho3D/LuaScript/pkgs/UI/UI.pkg
- Source/Urho3D/UI/Font.cpp
- Source/Urho3D/UI/Font.h
- Source/Urho3D/UI/FontFace.cpp
- Source/Urho3D/UI/FontFace.h
- Source/Urho3D/UI/FontFaceBitmap.cpp
- Source/Urho3D/UI/FontFaceFreeType.cpp
- Source/Urho3D/UI/FontFaceFreeType.h
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/Text.h
- Source/Urho3D/UI/Text3D.cpp
- Source/Urho3D/UI/Text3D.h
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UI.h
- Source/Urho3D/UI/UIBatch.cpp
- Source/Urho3D/UI/UIBatch.h
- bin/Data/LuaScripts/47_Typography.lua
- bin/Data/Scripts/47_Typography.as
When this option is enabled, text will be formatted with subpixel
(fractional) positions on the x-axis. Positions on the y-axis are
still pixel-aligned.
Note that this option has no effect if the hinting level is set
to FONT_HINT_LEVEL_NORMAL, as each glyph is rounded to an integral
pixel size by the hinter. It only makes a different if the hinting
mode is LIGHT (vertical hinting only) or NONE.
With subpixel positioning, the output will look blurrier due to
texture filtering. TODO: Add horizontal oversampling to improve
sharpness. That needs extra memory so it should be configurable.
> Add a 'subpixel glyph positions' option to UI (#1953)

- Source/Urho3D/Core/ProcessUtils.cpp
Different platform-specific functions return different values upon failure, for example one returns `String::EMPTY` while another returns `(?)`. From now on everything will return `(?)` if the function doesn't succeed.
> Minor incoherence fix

- Source/Urho3D/UI/FontFaceFreeType.cpp
Kerning values were being associated with the wrong char codes.
This was broken in commit 39930c9a, which moved some code around
to ensure that the space character is always the first one loaded.
> Fix kerning pairs (#2003)

- Docs/Reference.dox
- Source/Samples/47_Typography/Typography.cpp
- Source/Samples/47_Typography/Typography.h
- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/UI.pkg
- Source/Urho3D/UI/FontFace.h
- Source/Urho3D/UI/FontFaceFreeType.cpp
- Source/Urho3D/UI/FontFaceFreeType.h
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UI.h
- bin/Data/LuaScripts/47_Typography.lua
- bin/Data/Scripts/47_Typography.as
Subpixel-positioned text looks blurry, due to bilinear filtering of the
underlying texture. The basic idea here is to stretch the font glyphs
horizontally to increase the sharpness at subpixel positions. Note that
the stretched images need to be smoothed to avoid aliasing artifacts;
this is done in the FontFaceFreeType::BoxFilter() method.
Glyphs are always pixel-aligned vertically, so no vertical oversampling
is needed.
To make this feature comprehensible (I hope!) I've removed the
'subpixelGlyphPositions' flag and replaced it with a couple of values:
'fontSubpixelThreshold' sets the point at which subpixel positioning
kicks on, and 'fontOversampleLimit' caps the maximum amount of stretching.
The default values are 12pt text and max 3x oversampling. These are fairly
conservative …
> Add configurable oversampling to improve subpixel font rendering (#1953)

- Source/Urho3D/AngelScript/GraphicsAPI.cpp
- Source/Urho3D/AngelScript/MathAPI.cpp
- Source/Urho3D/Audio/SoundSource3D.cpp
- Source/Urho3D/Graphics/DebugRenderer.cpp
- Source/Urho3D/Graphics/DebugRenderer.h
- Source/Urho3D/LuaScript/pkgs/Graphics/DebugRenderer.pkg
- Source/Urho3D/LuaScript/pkgs/Math/Sphere.pkg
- Source/Urho3D/Math/Sphere.cpp
- Source/Urho3D/Math/Sphere.h
I also want to re-use AddSphereSector for drawing SoundSource3D.
IMO it's more fair because sector is circle, not pyramidal.
Any objections?
Before:
After:
> Add DebugRenderer::AddSphereSector. Expose Sphere helper funcions.

- Source/Urho3D/UI/FontFaceBitmap.cpp
Commit 0450bcd1 added two extra fields to FontGlyph, texWidth_ and texHeight_,
but these weren't being initialized for bitmap fonts.
Bitmap text would sometimes randomly look OK if the uninitialized fields
contained large numbers, and fail if the fields contained zeroes.
> Fix uninitialized FontGlyph fields in FontFaceBitmap (closes #2035)

- CMake/Modules/CheckHost.cmake
Also works correct when path contains spaces
> Fix mklink test when current path is not sources dir (for example whe used cmake-gui)

- Source/Urho3D/AngelScript/Urho2DAPI.cpp
- Source/Urho3D/Urho2D/TileMap2D.cpp
- Source/Urho3D/Urho2D/TileMap2D.h
- Source/Urho3D/Urho2D/TileMapLayer2D.cpp
- Source/Urho3D/Urho2D/TmxFile2D.cpp
- Source/Urho3D/Urho2D/TmxFile2D.h
This PR contains several tilemaps improvements and bugfixes:
- Added support for tilesets, based on collections of images
- Added support for tile collision object groups
- Fixed debug drawing of isometric rectangle and circle objects
- Fixed tilemap debug drawing when node is transformed
Actually, this does not seems completed, I wanted to ask your advice on how to make these right:
1. I wrote function TransformNode2D(Vector2), it is simple helper function, which transforms Vector2 from node's local space to global space. It is used in two classes, and now I just declare it in one class and define in another. Where I should put it? I'm not sure, it doesn't looks so generic to put it in Node class.
2. To load tile collision object group, I copy TileMapInfo2D structure into local var and …
> Several tilemap improvements

- Source/Urho3D/IK/IKEffector.cpp
This should fix the "(0,0,0) effector" bug.
IKEffector can either explicitly be given a target position with ```SetTargetPosition()```, or it can be given a node name to "follow", in which case IKEffector will search the scene for a matching node name right before solving.
The problem was that it would still perform this search, even with an empty node name. This behaviour is clearly wrong.
> IKEffector target bug fix

- Android/src/org/libsdl/app/SDLActivity.java
In some cases old activity may be destroyed after new activity is created. `onCreate()` of new activity gets called and initializes new activity as well as static variables, then `onDestroy()` is called on old activity and cleans up static variables that were just initialized by new activity. This change prevents calling `SDLActivity.initialize()` in `onDestroy()` if new activity has already reinitialized static variables.
> Fix crash on android

- Docs/Reference.dox
Okay, I suppose someone should try to do it at some point. I updated code standard with C++11 items.
They are more advisory than mandatory but I hope they will prevent style mess in the Urho codebase.
I tried to not cutoff useful C++11 features on the one hand, and keep old code more or less consistent with the new one on the other hand.
I understand that some items are potentially disputable, but I really tried to balance opinions mentioned on the Forum. So, this PR is the last chance to discuss freely.
I still heavily rely on the common sence of contributors. At least, let's document the basic guideline for this common sence.
> Update coding conventions for C++11.

- Source/Urho3D/Core/Context.cpp
- Source/Urho3D/Core/Variant.cpp
- Source/Urho3D/Core/Variant.h
- Source/Urho3D/IO/Deserializer.cpp
- Source/Urho3D/IO/Serializer.cpp
1. Varaint is able to store any custom type
2. Types are stored without memory allocation if `sizeof(Type) <= sizeof(void*)*2`
3. It is guaranteed that there is no internal allocations if assign the same type again (either directly or inside another Variant)
4. It is guaranteed that assignment operator is called in this case
5. ~~Custom types cannot be compared to either custom type or zero~~
6. Custom types cannot serialized
7. Custom types can be converted to string, compared to zero or each other if traits are specialized
The main purpose was to type-safely store pointers in the Variant.
> Make Variant able to store any type.

- Source/Urho3D/Physics/Constraint.cpp
Bypasses the check for same type if no constraint created yet. Fixes #2116.
Arguably it could be cleaner to have a "none" constraint type initially, this way either deserialization or programmatic creation could set the correct type, without having to worry of creating a default type constraint uselessly first.
> Fix programmatic point constraint creation after RigidBody component

- Source/Urho3D/Urho2D/CollisionShape2D.cpp
`ApplyNodeWorldScale` works well in the fixtureless case: it calls `RecreateFixture` which scales the shape, as expected, but ignores the fixture and the body when they are not there to start with: https://github.com/urho3d/Urho3D/blob/14bdd868e8db33c2e9193ed26ac57dbca510142d/Source/Urho3D/Urho2D/CollisionShape2D.cpp#L237 and https://github.com/urho3d/Urho3D/blob/14bdd868e8db33c2e9193ed26ac57dbca510142d/Source/Urho3D/Urho2D/CollisionShape2D.cpp#L215.
> fix fixtureless 2D shape scaling; fixes #2111

- Source/Urho3D/UI/Menu.cpp
Typing keys that are an accelerator key would fire up Menu actions. In the case of issue #2100, U or Ctrl-U would be one way to cause the Editor quick action window to be closed, due to logic code in the Editor that causes each menu selection to close it.
Not sure if this is wanted in each case, but would seem to make sense, particularly if there are accelerators bound without qualifier.
> Disregard Menu accelerator keys when a LineEdit is focused

- Source/ThirdParty/AngelScript/source/as_callfunc_x64_gcc.cpp
A quick fix to AngelScript that was preventing me from using address sanitizer with Urho3D, fixed upstream in revision 2410.  See https://www.gamedev.net/forums/topic/691763-error-compiling-on-gccx64-with-address-sanitizer .
> Hot-fix to AngelScript: fixed compile with address sanitizer.

- Source/ThirdParty/kNet/src/MessageConnection.cpp
I don't know if I should make pull request to Urho or kNet, so I'll first try this place :)
If you call `kNet::MessageConnection::sendMessage()` with zero length data, one of the assertions will fail. The reason for this is that `kNet::NetworkMessage::Resize()` does not allocate memory for `data` if length is zero, which is perfectly logical. However the assertion in `kNet::MessageConnection::sendMessage()` does not take this into account. This PR fixes the assertion, so it does not care about NULL if length is also zero.
> Fix too strict assert in kNet.

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/LuaScript/pkgs/UI/Button.pkg
- Source/Urho3D/UI/Button.cpp
- Source/Urho3D/UI/Button.h
Possibly, it might be more appropriate to add this offset to the BorderImage class instead, although I can't think of a personal use-case for doing so. If others disagree, I can withdraw this PR and add the functionality to BorderImage instead.
> Add ability to specify an image offset in Button, to enable graying-out buttons that are disabled.

- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/ListView.pkg
- Source/Urho3D/UI/ListView.cpp
- Source/Urho3D/UI/ListView.h
Some helpers that make massive ListView item instertion 10 times faster
```
Text* rootItem = new Text(context_);
rootItem->SetText("Root");
rootItem->SetStyleAuto();
listView->DisableInternalLayoutUpdate();
listView->InsertItem(M_MAX_UNSIGNED, rootItem, nullptr);
for (int j = 0; j < 15; ++j)
{
auto tp1 = std::chrono::high_resolution_clock::now();
for (int i = 0; i < 1000; ++i)
{
Text* childItem = new Text(context_);
childItem->SetStyleAuto();
childItem->SetText("Level" + String(j) + "Item" + String(i));
listView->InsertItem(1000 * j / 2, childItem, rootItem);
}
auto tp2 = std::chrono::high_resolution_clock::now();
unsigned dur = std::chrono::duration_cast<std::chrono::milliseconds>(tp2 - tp1).count();
URHO3D_LOGINFOF("j=%d t=%u", j, dur);
}
listView->EnableInternalLayoutUpdate(); …
```
> Add internal layout functions for ListView.

- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/Core/Context.h
- Source/Urho3D/Core/Object.h
- Source/Urho3D/Core/Variant.cpp
- Source/Urho3D/Graphics/Texture2D.cpp
- Source/Urho3D/Graphics/Texture2D.h
- Source/Urho3D/LuaScript/pkgs/UI/ScrollView.pkg
- Source/Urho3D/LuaScript/pkgs/UI/UIElement.pkg
- Source/Urho3D/Physics/PhysicsWorld.cpp
- Source/Urho3D/UI/ListView.cpp
- Source/Urho3D/UI/ScrollView.cpp
- Source/Urho3D/UI/ScrollView.h
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/Text.h
- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UIElement.cpp
- Source/Urho3D/UI/UIElement.h
- Add ScrollView horizontal/vertical bar visibility properties.
- Non-functional refactoring of wheel handling. Allows user to override wheel handling for custom UIElement.
- Add UIElement::IsChildOf helper function.
- Add allocation-less version of Texture2D::GetImage.
- Hide added item in hierarchy ListView if parent item is collapsed. This is old bug could be easily reproduced in the editor: just all new component/node for collapsed parent.
- Fix crash when GImpactMesh is collided with TriangleMesh.
- Add template version of Context::RegisterSubsystem.
- Make Object::IsInstanceOf return tested type.
- Rename Variant custom type strings.
> Misc fixes and features #2

- Source/Urho3D/UI/UI.cpp
- Source/Urho3D/UI/UI.h
- Source/Urho3D/UI/UIComponent.cpp
- Source/Urho3D/UI/UIComponent.h
- Source/Urho3D/UI/UIElement.cpp
- Source/Urho3D/UI/UIElement.h
Turns out 3D UI implementation was not flexible enough. This change allows ultimate freedom by splitting up responsibilities correctly.
UIComponent is no longer responsible for storing batches and vertex data. This information was moved to new `RenderToTextureData` struct inside `UI` subsystem. `UI` and `UIComponent` are no longer friends of each other.
New class `UIElement3D` was created. It is used as root UI element of UI rendered in a 3D scene. It implements `ScreenToElement()` method which is used for translating screen coordinates to element coordinates. Previously `UIComponent` did translation of these coordinates. `UIElement3D::ElementToScreen()` is not implemented at this time and returns `{-1, -1}` (invalid coordinates). It is also possible to set a custom viewport to root …
> 3D UI cleanup and update

- Source/Urho3D/AngelScript/Script.cpp
- Source/Urho3D/AngelScript/Script.h
- Source/Urho3D/AngelScript/ScriptInstance.cpp
Based on https://discourse.urho3d.io/t/enum-value-editing-via-editor/3804, I tried implementing the feature. As I personally don't use the editor for much, I can't say if this actually works (or that it won't eventually cause crashes potentially from the HashMap moving things around or the like), but I can say that enum attributes do show up in the editor now for ScriptInstances, and that they seem to be serialized to the scene when it is saved and then loaded when the scene is loaded.
So, its only the last commit (58ee22c) that I meant to have with this pull request, the rest are from my personal branch -- what is the best way to go about fixing this?
> ScriptInstance Enum Attributes

- Source/Urho3D/Graphics/View.cpp
Appears that at least on current Nvidia drivers, resolving from backbuffer to a multisampled texture to continue the rendering / pingpong process does not work on all APIs, but produces a black screen. On OpenGL it seems to work even now.
Therefore this PR reverts the extra buffers allocated by View during rendering being multisampled at all.
> Revert multisampled substitute rendertargets 

- Source/Urho3D/Graphics/Direct3D11/D3D11ShaderVariation.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9ShaderVariation.cpp
- Source/Urho3D/Graphics/OpenGL/OGLShaderProgram.cpp
- Source/Urho3D/Graphics/ShaderVariation.cpp
- Source/Urho3D/Graphics/ShaderVariation.h
Addresses  #2246.
I was unfortunately unable to test the DirectX cases, as I am on Linux here.  It would be great if someone could run the PBR sample with D3D9 and D3D11, with these changes, just to confirm everything is ok.
> Coverity shader parameters CID127650

- Source/Urho3D/Graphics/Direct3D11/D3D11Texture2D.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11Texture2DArray.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11Texture3D.cpp
- Source/Urho3D/Graphics/Direct3D11/D3D11TextureCube.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture2D.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture2DArray.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTextureCube.cpp
Closes #2253 and #2165
As #2165 mentions, these checks used to be there but were removed when textures were last reorganized some.
> Use mipmap levels of 1 when texture usage is TEXTURE_DYNAMIC

- Source/Samples/49_Urho2DIsometricDemo/CMakeLists.txt
- Source/Samples/50_Urho2DPlatformer/CMakeLists.txt
Samples 49_Urho2DIsometricDemo and 50_Urho2DPlatformer fail in the build process when URHO3D_URHO2D is not selected in CMake configuration. This pull request resolves it.
> Added URHO3D_URHO2D guard that seems omitted

- Source/Urho3D/Urho2D/Sprite2D.cpp
There was some bug noticed by @kostik1337 
There were same artifacts in newly added demos by @thesquib
I suppose that small non-zero default edge (0.00005f) should be used by default, since it most likely doesn't disturb any rendering, but prevent atlases from leaking edges (as far as I could see).
> Use non-zero default edge offset for Sprite2D.

- Source/Urho3D/Urho2D/Renderer2D.cpp
Hello everyone, I recently used StaticSprite2D to study the relationship between SetLayer andposition.z and found that z has priority over SetLayer. Layers only work when z is equal. I looked at the unity engine and found that it was the opposite. It was to consider layer first and then consider z. Which kind of order is universal? Should we be consistent with unity?
> Fixed the 2D rendering order makes the layer priority higher than the Z

- Source/ThirdParty/SDL/src/video/android/SDL_androidevents.c
Fixes #2328.
Previous behaviour allowed main loop to spin (at 10fps, as if window is minimized) while application was in background. This is both bad for battery life and also introduces a race condition where rapidly suspending and resuming application may get it into the state where application is resumed while some or most GPU objects are not recreated.
> Re-enable suspending main loop when application is paused on android

- Source/Urho3D/Core/ProcessUtils.cpp
Nothing fancy. The patch updated `GetOSVersion()` to recognize newer macOS versions, i.e. High Sierra and Mojave. Also more precise version reporting on some older versions.
> GetOSVersion() update for macOS

- CMake/Modules/UrhoCommon.cmake
- Source/Urho3D/Math/Matrix3x4.h
Remove '-ffast-math' option.
Remove GCC 8.x check in Matrix3x4.h
-ffast-math dangerous option.
> Fix for #2326

- Docs/AngelScriptAPI.h
- Docs/LuaScriptAPI.dox
- Docs/ScriptAPI.dox
- Source/Urho3D/AngelScript/NavigationAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Navigation/NavigationMesh.pkg
- Source/Urho3D/Navigation/CrowdAgent.cpp
- Source/Urho3D/Navigation/DynamicNavigationMesh.cpp
- Source/Urho3D/Navigation/NavigationMesh.cpp
- Source/Urho3D/Navigation/NavigationMesh.h
Correcting a typo on Source/Urho3D/Navigation/NavigationMesh.h 's API. This patch also corrects all usages inside of the urho repo, and it builds. Might break client code for some users, so buyer's beware.
> Fixing typo on NavigationMesh API

- Source/Urho3D/UI/UI.cpp
Fix: UI layout optimization does not take into account layout spaceing.
> Fix skipped visible elements due to UI layout optimization.

- Source/ThirdParty/SLikeNet/Source/src/linux_adapter.cpp
On Android device, the SLikeNet library crashes with a **__stack_chk_fail.** 
Because when the variable **l_prefix** is 128, the variable **i** is 16. The code line try to write l_mask[16] made the crash.
I fixed this bug with reference to libuv.
[https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/src/unix/android-ifaddrs.c](url)
> Fix SLikeNet crash on android device.

- Source/Urho3D/IO/Log.h
Fixed URHO3D_LOGTRACEF(message) parameters mismatch when disable log module.
> If disable Log module, URHO3D_LOGTRACEF(message) will cause parameters mismatch

- Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h
Compilation fails on FreeBSD 12.0 with the default compiler clang version 6.0.1:
```
[ 19%] Building CXX object Source/ThirdParty/SLikeNet/CMakeFiles/SLikeNet.dir/Source/src/RakString.cpp.o
/home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/src/RakString.cpp:1392:17: error: no matching function for call to 'vsnprintf_s'
int numChars = vsnprintf_s(stackBuff, 511, str, ap);
^~~~~~~~~~~
/home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h:42:5: note: candidate function not viable: requires 5 arguments, but 4 were provided
int vsnprintf_s(char *buffer, size_t sizeOfBuffer, size_t count, const char *format, va_list argptr);
```
A template is conditionally defined but the condition did not include FreeBSD.
> Make the 4 arguments vsnprintf_s() visible to FreeBSD

- Source/ThirdParty/StanHull/hull.cpp
Compilation fails on FreeBSD 12.0 with the default compiler clang version 6.0.1:
```
[ 12%] Building CXX object Source/ThirdParty/StanHull/CMakeFiles/StanHull.dir/hull.cpp.o
/home/romain/Projects/Urho3D/Source/ThirdParty/StanHull/hull.cpp:2590:28: error: cannot initialize return object of type 'int' with an rvalue of type 'nullptr_t'
if(verts_count <4) return NULL;
^~~~
/usr/include/sys/_null.h:37:14: note: expanded from macro 'NULL'
#define NULL    nullptr
^~~~~~~
1 error generated.
```
The function `overhull()` is supposed to return an `int`, but `NULL` is defined as a nullptr, which the compiler does not allow you to store as an int.
The fix consist in replacing `NULL` with the raw value `0`.
> Return 0, not NULL, in function returning an int

- Source/Urho3D/CMakeLists.txt
Compilation fails on FreeBSD 12.0 with the default compiler clang version 6.0.1:
```
[ 53%] Building CXX object Source/Urho3D/CMakeFiles/Urho3D.dir/Core/ProcessUtils.cpp.o
In file included from /home/romain/Projects/Urho3D/Source/Urho3D/Core/ProcessUtils.cpp:41:
In file included from /home/romain/Projects/Urho3D/build/include/Urho3D/ThirdParty/LibCpuId/libcpuid.h:88:
/home/romain/Projects/Urho3D/build/include/Urho3D/ThirdParty/LibCpuId/libcpuid_types.h:61:29: error: typedef redefinition with different types ('long long' vs '__int64_t' (aka 'long'))
typedef signed long long   int64_t;
^
/usr/include/sys/_stdint.h:51:20: note: previous definition is here
typedef __int64_t               int64_t;
^
In file included from /home/romain/Projects/Urho3D/Source/Urho3D/Core/ProcessUtils.cpp:41:
In …
```
> Fix conflicting types for int64_t and uint64_t on FreeBSD

- Source/ThirdParty/SLikeNet/CMakeLists.txt
[ 19%] Building CXX object Source/ThirdParty/SLikeNet/CMakeFiles/SLikeNet.dir/Source/src/BitStream.cpp.o
In file included from /home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/src/BitStream.cpp:48:
/home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h:17:10: fatal error: 'winsock2.h' file not found
#include "winsock2.h"
^~~~~~~~~~~~
1 error generated.
> Fix build using FreeBSD clang version 6.0.1

- Source/Urho3D/AngelScript/UIAPI.cpp
- Source/Urho3D/LuaScript/pkgs/UI/ToolTip.pkg
- Source/Urho3D/UI/ToolTip.cpp
- Source/Urho3D/UI/ToolTip.h
In working with ToolTips I've found that it's good to be able to hide them at will for stuff like repositioning, and alternative targets works well for setting a ToolTip for a layout or similar (say a row with a Text and a LineEdit) where normally the objects inside it would eat the input.
> Tooltip improvements

- Source/ThirdParty/SLikeNet/CMakeLists.txt
Compilation fails on FreeBSD 12.0 with the default compiler clang version 6.0.1:
```
[ 19%] Building CXX object Source/ThirdParty/SLikeNet/CMakeFiles/SLikeNet.dir/Source/src/BitStream.cpp.o
In file included from /home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/src/BitStream.cpp:48:
/home/romain/Projects/Urho3D/Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h:17:10: fatal error: 'winsock2.h' file not found
#include "winsock2.h"
^~~~~~~~~~~~
1 error generated.
```
This is dues to the way `inet_pton()` and `inet_ntop()` are looked for at the CMake level: Linux only requires `arpa/inet.h` but FreeBSD needs a few more includes as documented in the man page:
```
NAME
inet_aton, inet_addr, inet_network, inet_ntoa, inet_ntoa_r, inet_ntop,
inet_pton, inet_makeaddr, …
```
> Add missing headers for checking inet_pton() and inet_ntop() usability on FreeBSD

- Source/Urho3D/LuaScript/pkgs/Graphics/AnimationState.pkg
AnimationState needs to have the Apply function binding for lua. Needed for bone-less animation playback without animation controller. Not sure why it was missing in the first place, I assume it got forgotten.  For reference I followed 'Node animations' instructions in the documentation, which explicitly mentions the method. 
Works as intended in my project.
> added missing 'Apply' function for AnimationState

- Source/Urho3D/Graphics/DebugRenderer.cpp
- Source/Urho3D/Graphics/DebugRenderer.h
The `AddLine` calls were missing the `depthTest` flag, so it was impossible to actually get a sphere sector without depth test enabled.
Also added more details to the documentation for that function. Perhaps the documentation could be clarified differently, particularly regarding the angle. I initially expected the angle to range from 0 to 180 and be measured from the axis to the edge of the sector, but instead it ranges from 0 to 360 measuring the edge to the other edge of the sector.
> Fixed the depth test behavior of debug renderer sphere sectors.

- Source/Urho3D/Engine/Console.cpp
- bin/Data/UI/DefaultStyle.xml
LOG_TRACE offset the log levels by 1 but the console styling did not add a
trace styling, so warnings were printed with error styling, etc.
I've not tested this much, but if you just open up the console in one of the samples it seems to print as expected. (To get an error you can run an invalid command through the FileSystem and to get regular text you can run echo hello or something like that)
I went with a sort of yellow-gray for the trace text styling. Feel free to change it as you see fit, I was more concerned with getting errors and warnings to be the right color than choosing the best color for the trace text, so I just went with something that seemed maybe reasonable (I haven't actually seen it as text, so that remains to be confirmed).
> Fixed console styling to account for the addition of LOG_TRACE

- Source/Urho3D/UI/UI.cpp
This change prevents the following code from resulting in a segmentation fault:
```
UI* ui{ GetSubsystem<UI>() };
ui->SetCursor(new Cursor(context_));
ui->SetCursor(ui->GetCursor());
```
Thanks to @TIG3R99 for [locating](https://discourse.urho3d.io/t/changing-cursors/5581) this bug.
> Added check for setting cursor to current

- Source/Tools/SpritePacker/SpritePacker.cpp
If the forth parameter is "packerInfos.Size()" in "stbrp_init_target", I cannot pack three image(1920 * 1080、355 * 2 and 2 * 774) into a big image（2048 * 2048）.
In nothing/stb/stb_rect_pack.h comments, note that to guarantee best results, either:
1. make sure 'num_nodes' >= 'width'
or  2. call stbrp_allow_out_of_mem() defined below with 'allow_out_of_mem = 1'
See it in [](https://github.com/nothings/stb/blob/master/stb_rect_pack.h) line 124 to 143
:( bad on English
> fix bug for SpritePacker in Tools

- Source/Urho3D/Core/Timer.cpp
When the application is running for a long time in a browser environment,  emscripten_get_now()*1000.0 may larger than 2^32-1, so HiresTick() may return wrong value, which causes timeStep_ is always 0.0f.
> Fix HiresTimer overflow bug.

- Source/Urho3D/Graphics/OpenGL/OGLTexture.cpp
This caused pvr textures can't display on iOS devices.
Texture for testing :  [https://tmpfiles.org/dl/28949/bj.pvr](url)
> Fix wrong pvrtc data size.

- Source/Urho3D/AngelScript/Addons.cpp
- Source/Urho3D/AngelScript/MathAPI.cpp
Fix error in AngelScript API "bool Sphere::opEquals"
It was "bool& Sphere::opEquals" and in AngelScript was always true.
Fix error in AngelScript's autowrapper for generic calling convention for ARM64 in functions with ?& parameters. It is rewrite by manual register. On Android arm64-v8a it led to segviolation in using Dictionary in AngelScript.
> Fix error in AngelScript bindings

- Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp
- Source/Urho3D/Graphics/Direct3D9/D3D9Graphics.cpp
- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
Fixed D3D9 problem where switching to fullscreen on different monitor than the one the current device is created causes infinite device lost events and crash.
Fixed D3D11 issue where switching monitors when in borderless and fullscreen modes doesn't move the window on proper monitor.
> Fix Graphics::SetMode() issues with multiple monitors

- Source/Urho3D/UI/ProgressBar.cpp
Progress bar in vertical mode was scaling from top to bottom, the correct way on this mode is from bottom to top.
> Fix Progress Bar direction #2050

- Source/Urho3D/AngelScript/NetworkAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Network/Network.pkg
- Source/Urho3D/Network/Connection.cpp
- Source/Urho3D/Network/Network.cpp
- Source/Urho3D/Network/Network.h
- Now you can send messages through urho networking using message ID as unsigned int, instead of byte (only urho messages, SLiketNet messages keep the same thing).
- Is possible to set the max connections of Urho server, on **Network::StartServer** function. Before was allowed only 128 connections, and you couldn't change it.
> Network Changes

- Source/Urho3D/Container/Vector.h
My first attempt at a solution to #2563. I'm certainly open to other options if anyone can think of a better approach to this. I'm pretty sure the issues described in #1556 may still affect this when pushing a single item from the old vector.
Do you think it might be better to go with a more complete change like was done with PR #1561?
> Add check for Pushing *this to PODVector

- Source/Urho3D/Engine/Console.cpp
- bin/Data/UI/DefaultStyle.xml
> Console message type style fixed

- Source/Urho3D/Input/Input.cpp
- Source/Urho3D/Input/Input.h
- Source/Urho3D/Input/InputEvents.h
Get the clicks from SDL_MouseButtonEvent and send it on Urho Event (E_MOUSEBUTTONDOWN and E_MOUSEBUTTONUP).
This is useful for detect double click (or more) without use UI Event.
> Send Mouse Clicks on Event

- bin/Data/Scripts/Editor/EditorTerrain.as
- bin/Data/UI/EditorTerrainWindow.xml
Now is possible to leave from painting mode on Terrain Editor . You can simply press the button to reset window next to close button on title bar, or close/hide Terrain Editor window.
I added the reset button to Terrain Window, this is the only difference. Button will set edit mode to "Raise or lower terrain" and clear selected brush.
> Fix Terrain Editor brush #2471

- Source/Urho3D/Urho2D/AnimatedSprite2D.cpp
I updated **AnimatedSprite2D.cpp** to support Spine version 3.7 and 3.8
In a nutshell:
- **flipX/Y** became **scaleX/Y**
Followed instructions at http://esotericsoftware.com/forum/Spine-Unity-3-6-to-3-7-Upgrade-Guide-10446
- **spRegionAttachment_computeWorldVertices** gets two additional parameters and **spVertexAttachment_computeWorldVertices** gets replaced by **spMeshAttachment_computeWorldVertice**
Followed instructions at http://esotericsoftware.com/forum/Upgrading-QML-plugin-to-latest-c-runtime-9419
- **SP_ATTACHMENT_SKINNED_MESH** goes away.
Followed instructions at http://zh.esotericsoftware.com/forum/Updating-to-latest-spine-c-runtime-6720
- Other structural changes that were easy to follow (e.g. **slot->a/r/g/b** is **slot->color.a/r/g/b**)
I also created a sample cloning …
> Upgrade to support spine runtime 3.7 and above

- Source/Urho3D/AngelScript/PhysicsAPI.cpp
- Source/Urho3D/LuaScript/pkgs/Physics/RaycastVehicle.pkg
- Source/Urho3D/Physics/RaycastVehicle.cpp
- Source/Urho3D/Physics/RaycastVehicle.h
While playing with a heavy vehicle (small tank weighting 22 tons), the suspension had a strange behavior.
I tried solve it by setting the suspension stiffness and the maxtraveldistance.
That made the behavior much better, but still a bit wrong.
By exposing this bullet property all worked as I expected.
I don't know if there is a reason to keep this property from the Urho3D RaycastVehicle,...
> Add MaxSuspensionForce to RaycastVehicle

- Source/Samples/52_NATPunchtrough/NATPunchtrough.cpp
- Source/Samples/52_NATPunchtrough/NATPunchtrough.h
- Source/Urho3D/Network/Network.cpp
- Source/Urho3D/Network/Network.h
- Source/Urho3D/Network/NetworkEvents.h
When receiving disconnect from server we basically do a check if it's a NAT master server. If it is, we can skip the incorrect `E_SERVERDISCONNECTED` calls since NAT disconnect doesn't affect any live networking sessions, `E_NATMASTERDISCONNECTED` is sent instead and the users might handle those cases as they wish.
> NAT punchtrough master server disconnecting fix

- Source/Urho3D/Graphics/OpenGL/OGLIndexBuffer.cpp
- Source/Urho3D/Graphics/OpenGL/OGLRenderSurface.cpp
- Source/Urho3D/Graphics/OpenGL/OGLShaderProgram.cpp
- Source/Urho3D/Graphics/OpenGL/OGLShaderVariation.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture2D.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture2DArray.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTexture3D.cpp
- Source/Urho3D/Graphics/OpenGL/OGLTextureCube.cpp
- Source/Urho3D/Graphics/OpenGL/OGLVertexBuffer.cpp
- bin/shell.html
Wait till the viewport resizing is actually finished, then wait 1s to actually apply the new viewport size.
> Prevent canvas resize while the window size is still changing

- Source/Urho3D/Container/FlagSet.h
Made a PR to run CI just in case.
Having two impicit conversions to compatible types is clearly a design fault of `FlagSet` and shall be fixed until it fires somewhere else.
> Make FlagSet to bool conversion operator explicit. Fixes #2631.

- Source/Urho3D/Graphics/View.cpp
Allow `Camera::SetFlipVertical` to be used externally for OpenGL by toggling it either side of render to texture, i.e. instead of "set and clear" either side of render to texture.
The purpose of this pull request is to allow `Camera::SetFlipVertical` to be used for both DirectX and OpenGL to switch into a right handed coordinate system (see #2642). 
This pull request should not change the behaviour of any application that does not call `Camera::SetFlipVertical` directly. It also should correct the scenario where if the render to texture should not be flipped if the camera is already flipped (hence the toggling of state in the changes) 
Closes #2642
> Allow Camera::SetFlipVertical to be used externally for OpenGL

- bin/CoreData/Shaders/HLSL/PBRLitSolid.hlsl
This change removes a line of HLSL code that does not occur in the GLSL version of the code.
In my experiments I noticed that the environment mapping was much darker in DX9 vs OGL versions.
I tracked to the difference to be purely a consequence of this line of code, which in effect squares the darkening effect of the specular color.  I suspect this difference may not have been noticed because it makes no difference if the material specular color is full white.
It may be that it is the GLSL version that needs correcting to make it consistent with the HLSL version, but I'm not really sure why the HLSL version of this code would need to effectively multiply a specular color by itself. But in anycase, I think the HLSL and GLSL code should at least be consistent in this respect.
Too dark in …
> Image too dark for DX9 caused by mismatch between code PBRLitSolid.hlsl and PBRLitSolid.glsl  

- Source/Urho3D/Container/Vector.h
Added PODVector::Resize overload that fills new elements with a default value.
I think it's useful as the user may prefer something like PODVector<Vector3> to be extended with a "nice" value like Vector3::ZERO in some circumstances while not caring in the general case.
> Added PODVector::Resize overload with default value

- Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp
As was earlier [noted](https://github.com/urho3d/Urho3D/pull/2608#pullrequestreview-390630295), the incorrect relative includes of `Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp`,  shown below, causes redefinition errors during emscripten build ( observed with emscripten sdk v2.0.4 on win10 )
https://github.com/urho3d/Urho3D/blob/ebd7633f8916149212159d4a1cccfe1ac70c1da5/Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp#L55-L58
This fix resolves it.
> Fix incorrect relative includes to causes error during emscripten build

- Source/Urho3D/Graphics/CustomGeometry.cpp
- Source/Urho3D/UI/Sprite.cpp
- Source/Urho3D/UI/Text.cpp
- Source/Urho3D/UI/Text3D.cpp
- Source/Urho3D/UI/ToolTip.cpp
Silences various compiler warnings... missing enums in switch statement, esoteric associativity, intention safety. There are a few other warnings but these are the low hanging fruit.
> Silence compiler warnings

- CMake/Modules/CheckCompilerToolchain.cmake
- CMake/Modules/UrhoCommon.cmake
MCST e2k (Elbrus 2000) architecture has half native / half software support of most Intel/AMD SIMD
e.g. MMX/SSE/SSE2/SSE3/SSSE3/SSE4.1/SSE4.2/AES/AVX/AVX2 & 3DNow!/SSE4a/XOP/FMA4
- https://en.wikipedia.org/wiki/Elbrus_2000
> E2K: added use of x86 SIMD instruction set on MCST Elbrus 2000 CPU architecture

- Source/Urho3D/UI/UI.cpp
Remove division by 2 for cursor position because it is already in correct metrics
Issue on my mac:
> Fix clicks on retina display

- .gitignore
- Source/ThirdParty/SDL/src/video/cocoa/SDL_cocoavideo.h
Fix bug in third party library that prevents the engine from building on El Capitan. [edit: [context](https://discourse.libsdl.org/t/sdl-2-0-10-old-mac-os-el-capitan-10-11-and-xcode7-3/26554/7) and [the patch](https://gist.githubusercontent.com/illume/ac2eb4daa1bd805255d5355806acf822/raw/7e3c83f760fe5bf61a9f6bcc196ed9be6f6e22da/sdl2-mac-10-11.patch)]
Also updates the gitignore for some temporary files that aren't consumed if the 'dot' dependency is missing.
> Fix build bugs for OSX and when dot dependency is missing

- Source/Urho3D/IO/Log.cpp
- Source/Urho3D/IO/Log.h
Speeds up logging by only constructing formatted messages when the log level justifies it. Previously all formatted log macros were calling `Urho3D::ToString()` regardless of log level, which is expensive. This patch completely solves performance issues that I had encountered in a test case where trace log messages were being created needlessly.
Also reduces duplication in the logging macros by adding two new macros that take log level as input instead of putting it in the macro name.
```
URHO3D_LOG(level, message)
URHO3D_LOGF(level, format, ...)
```
edit: I am not sure if this is thread safe... anyone have an opinion/idea?
> Logging speedup

- bin/Data/Scenes/PBRExample.xml
There is a case issue with the heightmap texture name in `PBRExample.xml` scene file. Texture loading fails due to this issue.
https://github.com/urho3d/Urho3D/blob/master/bin/Data/Textures/HeightMap.png
> Fixed texture loading failure caused by Heightmap typo

- bin/Data/Scripts/Editor/EditorSpawn.as
Simple fix.
Additional thought: The editor spawn menu gives a checkbox that says "Spawn on selected node" when in reality it is more like "ensure all spawn positions are on selected node". Maybe it could be renamed to "Ensure spawning on selected node"?
> Fix conditional typo in EditorSpawn.as

- Source/Urho3D/Audio/Audio.cpp
@1vanK updated version as requested.
https://github.com/urho3d/Urho3D/issues/2718
Limit number of channels to avoid issues on multichannel audio device (5.1, 7.1, etc)
The issue is present on, for example, Logitech G933 headphones with surround sound enabled.
> Issue 2718 bugfix

- Source/Urho3D/Graphics/Drawable.cpp
Fix format dismatch error in WriteDrawablesToOBJ,.
When  use Drawable::WriteDrawablesToOBJ to produce an obj file in posix system, one of the face indice value will be deadly wrong, in my system environment(linux), it comes a super huge number that makes an error when trying to import that file with assimp.
On windows system, both  unsigned and unsigned long takes the same size, so everything goes in a right way with lucky. But on posix system, unsigned long takes double size than unsigned, which makes a memory reading problem. So modify "%l" to "%u" to ensure the type matching fixes this issue.
> Fix output obj file on linux system.

- website/news/2021-06-06-Bit-Champs.mdx
Hi,
This is an article about Bit Champs for the News section on Urho3D's website.
[This is the relevant discourse post](https://discourse.urho3d.io/t/new-release-bit-champs-and-our-first-project-with-urho3d/6877).
I tried to follow the guidelines in the other articles.
> News article about Bit Champs

- Source/Urho3D/Network/Connection.cpp
As we know, Urho3D supports the scenes in the JSON format (even the standard editor can export the scenes in JSON), but after connecting to the server when the scene is loading on the client side, the engine gives an error like "ERROR: Scene.json is not a valid scene file". This fix solves this problem.
> Fix Connection support JSON scene format on a client side

- Source/Tools/BindingGenerator/ASClassBinder.cpp
- Source/Tools/BindingGenerator/ASResult.cpp
- Source/Tools/BindingGenerator/ASResult.h
- Source/Tools/BindingGenerator/ASUtils.cpp
- Source/Tools/BindingGenerator/XmlAnalyzer.h
- Source/Urho3D/AngelScript/APITemplates.h
- Source/Urho3D/AngelScript/Generated_Classes.cpp
- Source/Urho3D/AngelScript/Generated_DefaultConstructors.cpp
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/AngelScript/Generated_ObjectTypes.cpp
- Source/Urho3D/AngelScript/Manual_Graphics.h
Registration in AngelScript of classes marked as @fakeref with the flag "asOBJ_NOCOUNT", without registration empty AddRef and Release. This optimizes the AngelScript code, as it disables the call to reference counting for such objects. In general, I think that for such objects, the registration of the factory should also be removed, since the objects created in the script through the factory will never be deleted.
> Remove FakeAddRef and FakeReleaseRef

- Source/Urho3D/Graphics/Material.cpp
Fixes #2826. Simple one line addition.
> Material::ResetToDefaults() should clear shaderParameterAnimationInfos_

- Source/Urho3D/Graphics/Material.cpp
I believe Material should also unsubscribe from the update events when we clear the shader animations in addition to clearing them. An additional fix for #2826
> Material unsubscribe from animation events on ResetToDefault

- Source/Samples/99_Benchmark/CMakeLists.txt
Fix for
```
CMake Error at Source/Samples/99_Benchmark/CMakeLists.txt:36 (source_group):
source_group ROOT:
/home/runner/work/Urho3D/Urho3D/Source/Samples/99_Benchmark is not a prefix
of file: /home/runner/work/Urho3D/Urho3D/build/ci/bin/Urho3D.js
```
in web builds
> 99_Benchmark: use standart way for source grouping

- Source/Tools/BindingGenerator/ASUtils.cpp
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Audio/Audio.cpp
- Source/Urho3D/Audio/Audio.h
- Source/Urho3D/Base/PrimitiveTypes.h
- Source/Urho3D/Container/VectorBase.h
1) In most modern compilers, the size of primitive types is same (except `long`), but not in the C++ standard. Therefore, it is common practice to use types with a fixed size (Uint32 in SDL for example).
2) C++11 define [fixed width integer types](https://en.cppreference.com/w/cpp/types/integer), but this type names are too long (`uint32_t` has the same length as `unsigned`).
3) `i4` is even shorter than `i32` but I don't use this variant because it can be confusing (i8 - 8 bits or 64 bits?). So I used [this variant](https://doc.rust-lang.org/book/ch03-02-data-types.html).
4) I'm not going to change type names whole the engine at once, I just added the ability to use new types when writing new code or changing old one.
> Allows short names for primitive types

- bin/Data/LuaScripts/49_Urho2DIsometricDemo.lua
- bin/Data/LuaScripts/Utilities/2D/Sample2D.lua
- added collision handling
- added debug drawing of tileMap stuff, as in the AS version
- also edited SpawnEffect in Sample2D.lua to match the AS version
(without the edit, the effect would spawn behind the scenario in sample 49)
> Complete 49_Urho2DIsometricDemo.lua (#2865)

- Source/Urho3D/Core/MiniDump.cpp
dbghelp not linking, when URHO3D_MINIDUMPS not defined, so MiniDumpWriteDump() used in WriteMiniDump() is not implemented
> Don't define WriteMiniDump when URHO3D_MINIDUMPS is not defined

- Source/Urho3D/Base/PrimitiveTypes.h
sizeof(char) always evaluate to 1
> Do not check size of char

- CMakeLists.txt
CMake < 3.15 use `/w3` by default. This cause the huge number of warnings in ThirdParty libs in VS. Owerriding `/w3` by `/w` cause another warning, which can also be disabled in CMake >= 3.15. CMake 3.15 is old enough to usage.
https://cmake.org/cmake/help/latest/policy/CMP0092.html
> Increase CMake minumum version to 3.15 [cache clear]

- Source/Urho3D/AngelScript/Generated_GlobalVariables.cpp
- Source/Urho3D/AngelScript/Generated_Includes.h
- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/Container/Vector.h
- Source/Urho3D/Container/VectorBase.cpp
- Source/Urho3D/Container/VectorBase.h
- Source/Urho3D/Network/Connection.h
- Source/Urho3D/Resource/Image.cpp
- Source/Urho3D/Resource/JSONValue.cpp
- Source/Urho3D/Scene/Node.cpp
- Source/Urho3D/Scene/Node.h
- Source/Urho3D/Scene/ValueAnimationInfo.cpp
- Source/Urho3D/UI/LineEdit.cpp
- Source/Urho3D/UI/ListView.cpp
- Source/Urho3D/UI/ScrollView.cpp
This creates a huge number of warnings, but everything seems to remain in working order. Warnings will be gradually fixed
NINDEX is analog of String::NPOS, but for vectors
> Vector: replace size, index & capacity types from unsigned to signed

- Source/Urho3D/AngelScript/Generated_Members.h
- Source/Urho3D/UI/UIElement.cpp
- Source/Urho3D/UI/UIElement.h
> UIElement: unsigned to signed

- Source/Urho3D/Graphics/AnimationState.h
Node is used in line 45 but has no forward declaration.
```
/// Scene node pointer.
WeakPtr<Node> node_;
```
> Forward Declare Node

- Source/Urho3D/Graphics/RenderPath.h
The full definition seems to be needed for `HashMap<StringHash, Variant> shaderParameters_;` and not just a (not present) forward declaration.
> Include Variant.h from RenderPath.h

- Source/Urho3D/IO/Log.cpp
Adds special case in Log::WriteFormat for LOG_RAW to match the behavior of Log::Write.
The introduction of WriteFormat in #2685 left LOG_RAW messages unprinted (messages like those produced by LuaScript::Print). Another alternate fix, though it would leave WriteFormat and Write with inconsistent behaviors, would be to return the URHO3D_LOGRAWF and URHO3D_LOGRAW macros to their old definitions from before #2685.
> Log::WriteFormat fails for LOG_RAW

- .github/workflows/main.yml
Emscripten was updated from version 3.1.17 to 3.1.18 and the engine stopped compiling
> Use previous version of Emscripten

- android/launcher-app/CMakeLists.txt
Perhaps there is a better way to set the environment variable in Android Studio, but I do not know it.
> Fix: samples not builded when compiled through Android Studio

- .github/workflows/main.yml
- Source/Urho3D/GraphicsAPI/Direct3D11/D3D11ShaderVariation.cpp
Upgraded Ubuntu have newest MinGW version
Issue: https://github.com/urho3d/Urho3D/issues/2887
Another PR: https://github.com/urho3d/Urho3D/pull/2936
> Check MinGW compatibility | Linux_MinGW forkflow: upgrade Ubuntu to 22.04

- Docs/Doxyfile.in
Motivation:
```
/// Set the Interpolation Mode.
/// @property
void SetInterpolationMode(InterpolationMode interpolationMode);
```
interpreted as a detailed description without brief description:
With enabled MULTILINE_CPP_IS_BRIEF entire comment is interpreted as brief.
To add detailed description empty line or `\details` command can be used:
```
/// Ssfsdfds (aaaaaaaaaa)
/// sdfsdfds
///
/// Detailed comment
int aaa;
/// SAdsafsdf
/// sdfsdfdsf
/// \details Detailed comment
float bbbb;
```
> Doxygen: enable MULTILINE_CPP_IS_BRIEF

- .gitignore
- Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c
In upstream SDL newer versions this is fixed - so updating SDL would also fix this issue.
The docs say the SDK is tested against emscripten 2.0.8, version 2.0.8 (all the way back to around 1.39 I believe?) require the setWindowTitle EM_ASM in SDL to be updated as is here.
Without this, building urho with emscripten 2.0.8 works, but all of the examples crash in chrome and firefox.
Also added a git ignore entry for vscode project files
> Fix setWindowTitle in emscripten SDL

- Source/Urho3D/Base/PrimitiveTypes.h
The underlying type of int64_t is different on different platforms
* gcc 32, clang 32, vs 32, vs 64 - long long
* gcc 64, clang 64 - long
This cause problems in some situations. For example `int64_t x; Variant(x);` just not compile on clang 64 (compiler cannot choose which of the integer constructors to use)
> PrimitiveTypes: do not use std::uint64_t and etc for underlying types

- android/launcher-app/src/main/AndroidManifest.xml
При сборке под свежим gradle без этого флага Android не распаковывает нативные либы и лончер не видит примеры для запуска.
> Fix Android launcher

- Source/ThirdParty/SDL/src/video/wayland/SDL_waylanddyn.h
- Source/ThirdParty/SDL/src/video/wayland/SDL_waylandsym.h
При сборке под Wayland 1.21 появляются ошибки линковки по типу:
```
undefined reference to `wl_proxy_get_version'
```
Вдохновившись этим патчем я заставил Urho3D собраться под Wayland 1.21.
https://github.com/libsdl-org/SDL/pull/5092
Движок всё ещё требует SDL_VIDEODRIVER=wayland чтобы запускаться под Wayland'ом, но в целом работает.
> Fix to build on wayland 1.21
